// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/chainloop-dev/chainloop/app/controlplane/pkg/data/ent/organization"
	"github.com/google/uuid"
)

// Organization is the model entity for the Organization schema.
type Organization struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// BlockOnPolicyViolation holds the value of the "block_on_policy_violation" field.
	BlockOnPolicyViolation bool `json:"block_on_policy_violation,omitempty"`
	// PoliciesAllowedHostnames holds the value of the "policies_allowed_hostnames" field.
	PoliciesAllowedHostnames []string `json:"policies_allowed_hostnames,omitempty"`
	// PreventImplicitWorkflowCreation holds the value of the "prevent_implicit_workflow_creation" field.
	PreventImplicitWorkflowCreation bool `json:"prevent_implicit_workflow_creation,omitempty"`
	// RestrictContractCreationToOrgAdmins holds the value of the "restrict_contract_creation_to_org_admins" field.
	RestrictContractCreationToOrgAdmins bool `json:"restrict_contract_creation_to_org_admins,omitempty"`
	// APITokenInactivityThresholdDays holds the value of the "api_token_inactivity_threshold_days" field.
	APITokenInactivityThresholdDays *int `json:"api_token_inactivity_threshold_days,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrganizationQuery when eager-loading is set.
	Edges        OrganizationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OrganizationEdges holds the relations/edges for other nodes in the graph.
type OrganizationEdges struct {
	// Memberships holds the value of the memberships edge.
	Memberships []*Membership `json:"memberships,omitempty"`
	// WorkflowContracts holds the value of the workflow_contracts edge.
	WorkflowContracts []*WorkflowContract `json:"workflow_contracts,omitempty"`
	// Workflows holds the value of the workflows edge.
	Workflows []*Workflow `json:"workflows,omitempty"`
	// CasBackends holds the value of the cas_backends edge.
	CasBackends []*CASBackend `json:"cas_backends,omitempty"`
	// Integrations holds the value of the integrations edge.
	Integrations []*Integration `json:"integrations,omitempty"`
	// APITokens holds the value of the api_tokens edge.
	APITokens []*APIToken `json:"api_tokens,omitempty"`
	// Projects holds the value of the projects edge.
	Projects []*Project `json:"projects,omitempty"`
	// Groups holds the value of the groups edge.
	Groups []*Group `json:"groups,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [8]bool
}

// MembershipsOrErr returns the Memberships value or an error if the edge
// was not loaded in eager-loading.
func (e OrganizationEdges) MembershipsOrErr() ([]*Membership, error) {
	if e.loadedTypes[0] {
		return e.Memberships, nil
	}
	return nil, &NotLoadedError{edge: "memberships"}
}

// WorkflowContractsOrErr returns the WorkflowContracts value or an error if the edge
// was not loaded in eager-loading.
func (e OrganizationEdges) WorkflowContractsOrErr() ([]*WorkflowContract, error) {
	if e.loadedTypes[1] {
		return e.WorkflowContracts, nil
	}
	return nil, &NotLoadedError{edge: "workflow_contracts"}
}

// WorkflowsOrErr returns the Workflows value or an error if the edge
// was not loaded in eager-loading.
func (e OrganizationEdges) WorkflowsOrErr() ([]*Workflow, error) {
	if e.loadedTypes[2] {
		return e.Workflows, nil
	}
	return nil, &NotLoadedError{edge: "workflows"}
}

// CasBackendsOrErr returns the CasBackends value or an error if the edge
// was not loaded in eager-loading.
func (e OrganizationEdges) CasBackendsOrErr() ([]*CASBackend, error) {
	if e.loadedTypes[3] {
		return e.CasBackends, nil
	}
	return nil, &NotLoadedError{edge: "cas_backends"}
}

// IntegrationsOrErr returns the Integrations value or an error if the edge
// was not loaded in eager-loading.
func (e OrganizationEdges) IntegrationsOrErr() ([]*Integration, error) {
	if e.loadedTypes[4] {
		return e.Integrations, nil
	}
	return nil, &NotLoadedError{edge: "integrations"}
}

// APITokensOrErr returns the APITokens value or an error if the edge
// was not loaded in eager-loading.
func (e OrganizationEdges) APITokensOrErr() ([]*APIToken, error) {
	if e.loadedTypes[5] {
		return e.APITokens, nil
	}
	return nil, &NotLoadedError{edge: "api_tokens"}
}

// ProjectsOrErr returns the Projects value or an error if the edge
// was not loaded in eager-loading.
func (e OrganizationEdges) ProjectsOrErr() ([]*Project, error) {
	if e.loadedTypes[6] {
		return e.Projects, nil
	}
	return nil, &NotLoadedError{edge: "projects"}
}

// GroupsOrErr returns the Groups value or an error if the edge
// was not loaded in eager-loading.
func (e OrganizationEdges) GroupsOrErr() ([]*Group, error) {
	if e.loadedTypes[7] {
		return e.Groups, nil
	}
	return nil, &NotLoadedError{edge: "groups"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Organization) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case organization.FieldPoliciesAllowedHostnames:
			values[i] = new([]byte)
		case organization.FieldBlockOnPolicyViolation, organization.FieldPreventImplicitWorkflowCreation, organization.FieldRestrictContractCreationToOrgAdmins:
			values[i] = new(sql.NullBool)
		case organization.FieldAPITokenInactivityThresholdDays:
			values[i] = new(sql.NullInt64)
		case organization.FieldName:
			values[i] = new(sql.NullString)
		case organization.FieldCreatedAt, organization.FieldUpdatedAt, organization.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case organization.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Organization fields.
func (_m *Organization) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case organization.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case organization.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case organization.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case organization.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case organization.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case organization.FieldBlockOnPolicyViolation:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field block_on_policy_violation", values[i])
			} else if value.Valid {
				_m.BlockOnPolicyViolation = value.Bool
			}
		case organization.FieldPoliciesAllowedHostnames:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field policies_allowed_hostnames", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PoliciesAllowedHostnames); err != nil {
					return fmt.Errorf("unmarshal field policies_allowed_hostnames: %w", err)
				}
			}
		case organization.FieldPreventImplicitWorkflowCreation:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field prevent_implicit_workflow_creation", values[i])
			} else if value.Valid {
				_m.PreventImplicitWorkflowCreation = value.Bool
			}
		case organization.FieldRestrictContractCreationToOrgAdmins:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field restrict_contract_creation_to_org_admins", values[i])
			} else if value.Valid {
				_m.RestrictContractCreationToOrgAdmins = value.Bool
			}
		case organization.FieldAPITokenInactivityThresholdDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_token_inactivity_threshold_days", values[i])
			} else if value.Valid {
				_m.APITokenInactivityThresholdDays = new(int)
				*_m.APITokenInactivityThresholdDays = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Organization.
// This includes values selected through modifiers, order, etc.
func (_m *Organization) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMemberships queries the "memberships" edge of the Organization entity.
func (_m *Organization) QueryMemberships() *MembershipQuery {
	return NewOrganizationClient(_m.config).QueryMemberships(_m)
}

// QueryWorkflowContracts queries the "workflow_contracts" edge of the Organization entity.
func (_m *Organization) QueryWorkflowContracts() *WorkflowContractQuery {
	return NewOrganizationClient(_m.config).QueryWorkflowContracts(_m)
}

// QueryWorkflows queries the "workflows" edge of the Organization entity.
func (_m *Organization) QueryWorkflows() *WorkflowQuery {
	return NewOrganizationClient(_m.config).QueryWorkflows(_m)
}

// QueryCasBackends queries the "cas_backends" edge of the Organization entity.
func (_m *Organization) QueryCasBackends() *CASBackendQuery {
	return NewOrganizationClient(_m.config).QueryCasBackends(_m)
}

// QueryIntegrations queries the "integrations" edge of the Organization entity.
func (_m *Organization) QueryIntegrations() *IntegrationQuery {
	return NewOrganizationClient(_m.config).QueryIntegrations(_m)
}

// QueryAPITokens queries the "api_tokens" edge of the Organization entity.
func (_m *Organization) QueryAPITokens() *APITokenQuery {
	return NewOrganizationClient(_m.config).QueryAPITokens(_m)
}

// QueryProjects queries the "projects" edge of the Organization entity.
func (_m *Organization) QueryProjects() *ProjectQuery {
	return NewOrganizationClient(_m.config).QueryProjects(_m)
}

// QueryGroups queries the "groups" edge of the Organization entity.
func (_m *Organization) QueryGroups() *GroupQuery {
	return NewOrganizationClient(_m.config).QueryGroups(_m)
}

// Update returns a builder for updating this Organization.
// Note that you need to call Organization.Unwrap() before calling this method if this Organization
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Organization) Update() *OrganizationUpdateOne {
	return NewOrganizationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Organization entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Organization) Unwrap() *Organization {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Organization is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Organization) String() string {
	var builder strings.Builder
	builder.WriteString("Organization(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("block_on_policy_violation=")
	builder.WriteString(fmt.Sprintf("%v", _m.BlockOnPolicyViolation))
	builder.WriteString(", ")
	builder.WriteString("policies_allowed_hostnames=")
	builder.WriteString(fmt.Sprintf("%v", _m.PoliciesAllowedHostnames))
	builder.WriteString(", ")
	builder.WriteString("prevent_implicit_workflow_creation=")
	builder.WriteString(fmt.Sprintf("%v", _m.PreventImplicitWorkflowCreation))
	builder.WriteString(", ")
	builder.WriteString("restrict_contract_creation_to_org_admins=")
	builder.WriteString(fmt.Sprintf("%v", _m.RestrictContractCreationToOrgAdmins))
	builder.WriteString(", ")
	if v := _m.APITokenInactivityThresholdDays; v != nil {
		builder.WriteString("api_token_inactivity_threshold_days=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Organizations is a parsable slice of Organization.
type Organizations []*Organization
