FROM golang:1.26.4@sha256:68cb6d68bed024785b69195b89af7ac7a444f27791435f98647edff595aa0479 AS builder
RUN mkdir -p /.config/chainloop

FROM scratch

COPY ./chainloop /
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder --chown=1001:1001 /.config/chainloop /.config/chainloop

USER 1001

ENTRYPOINT [ "./chainloop"]
