FROM golang:1.26.2@sha256:2a2b4b5791cea8ae09caecba7bad0bd9631def96e5fe362e4a5e67009fe4ae61 AS builder
RUN mkdir -p /.config/chainloop

FROM scratch

COPY ./chainloop /
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder --chown=1001:1001 /.config/chainloop /.config/chainloop

USER 1001

ENTRYPOINT [ "./chainloop"]
