FROM golang:1.26.1@sha256:c7e98cc0fd4dfb71ee7465fee6c9a5f079163307e4bf141b336bb9dae00159a5 AS builder
RUN mkdir -p /.config/chainloop

FROM scratch

COPY ./chainloop /
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder --chown=1001:1001 /.config/chainloop /.config/chainloop

USER 1001

ENTRYPOINT [ "./chainloop"]
