# Copyright Chainloop, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

apiVersion: v2
name: chainloop
description: Chainloop is an open source software supply chain control plane, a single source of truth for artifacts plus a declarative attestation crafting process.

type: application
# Bump the patch (not minor, not major) version on each change in the Chart Source code
version: 1.89.0
# Do not update appVersion, this is handled automatically by the release process
appVersion: v0.95.7

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.x.x
  - condition: development
    name: vault
    repository: https://charts.bitnami.com/bitnami
    version: 1.4.x
  - condition: development
    repository: file://charts/dex
    name: dex
    version: 0.0.x

annotations:
    images: |
        - image: ghcr.io/chainloop-dev/chainloop/artifact-cas:v0.95.7
          name: artifact-cas
        - image: ghcr.io/chainloop-dev/chainloop/control-plane:v0.95.7
          name: control-plane
        - image: ghcr.io/chainloop-dev/chainloop/control-plane-migrations:v0.95.7
          name: control-plane-migrations
