# This indicates the [current version]+next
# to indicate that we are building a new version of the project
projectVersion: v1.61.0+next

# Experimental feature used by Chainloop labs shared workflow https://github.com/chainloop-dev/labs
# It maps the material names with location in disk so they get automatically attested

scorecards:
  - name: sarif-results
    path: metadata/results.sarif
