# Experimental feature used by Chainloop labs shared workflow https://github.com/chainloop-dev/labs
# It maps the material names with location in disk so they get automatically attested
docs:
  - name: sbom-cdx
    path: docs/reports/sbom.cyclonedx.json
  - name: sbom-spdx
    path: docs/reports/sbom.spdx.json
  - name: built-site
    path: docs/reports/build.tar.gz
