# This can indicate the next version and by default it will be marked as pre-release
projectVersion: v0.161.0

# Experimental feature used by Chainloop labs shared workflow https://github.com/chainloop-dev/labs
# It maps the material names with location in disk so they get automatically attested
docs:
  - name: sbom-cdx
    path: reports/sbom.cyclonedx.json
  - name: sbom-spdx
    path: reports/sbom.spdx.json
  - name: built-site
    path: reports/build.tar.gz

scorecards:
  - name: sarif-results
    path: metadata/results.sarif
