run:
  timeout: 10m

linters:
  # Note that there are some linters enabled by default, see golang-ci linters
  enable:
    - goheader
    - dupl
    - gofmt
    - goimports
    - misspell
    - nakedret
    - revive
    - gosec
    - asciicheck
    - whitespace
    - errorlint
    - forbidigo
    - gocritic
    - importas
    - prealloc
    - stylecheck
    - unconvert
    - dogsled
    - goconst
    - exportloopref
    - gocyclo
    - goprintffuncname
    # Can't enable it for now, it crashes https://github.com/ent/ent/pull/3315
    # - unparam

linters-settings:
  gofmt:
    simplify: true
  dupl:
    threshold: 400
  goheader:
    template: |-
      Copyright {{copyright-year}} The Chainloop Authors.

      Licensed under the Apache License, Version 2.0 (the "License");
      you may not use this file except in compliance with the License.
      You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

      Unless required by applicable law or agreed to in writing, software
      distributed under the License is distributed on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
      See the License for the specific language governing permissions and
      limitations under the License.
    values:
      regexp:
        copyright-year: 202[3]
  forbidigo:
    forbid:
      - ^print.*$
      - '^t\.Error.*$(# forbid t.Error in favor of using testify\.)?'
      - '^t\.Fatal.*$(# forbid t.Fatal in favor of using testify\.)?'
