schemaVersion: v1
runner:
  type: GITHUB_ACTION
materials:
  - type: SARIF
    name: sarif-results
    output: true
policies:
  attestation:
    - ref: source-commit
  materials:
    - ref: vulnerabilities
      with:
        severity: MEDIUM
    - ref: cves-in-kev
