apiVersion: chainloop.dev/v1
kind: Contract
metadata:
  # DO NOT CHANGE, it's used in the getting started guide
  # https://docs.chainloop.dev/get-started
  name: myproject-build-container-image
  description: Basic contract with materials only
spec:
  materials:
    - name: container
      type: CONTAINER_IMAGE
    - name: sbom
      type: SBOM_CYCLONEDX_JSON
    - name: vulnerabilities-report
      type: SARIF
