apiVersion: chainloop.dev/v1
kind: Contract
metadata:
  # DO NOT CHANGE, it's used in the getting started guide
  # https://docs.chainloop.dev/get-started
  name: myproject-build-container-image
  description: Contract with policies for OSS projects
spec:
  materials:
    - name: container
      type: CONTAINER_IMAGE
    - name: sbom
      type: SBOM_CYCLONEDX_JSON
    - name: vulnerabilities-report
      type: SARIF

  # We can attach policies from the provided library of policies https://app.chainloop.dev/policies
  # or custom ones as explained here https://docs.chainloop.dev/concepts/policies
  policies:
    attestation:
      - ref: https://raw.githubusercontent.com/chainloop-dev/chainloop/refs/heads/main/docs/examples/policies/chainloop-commit.yaml
      - ref: https://raw.githubusercontent.com/chainloop-dev/chainloop/refs/heads/main/docs/examples/policies/sbom/sbom-present.yaml
    materials:
      - ref: https://raw.githubusercontent.com/chainloop-dev/chainloop/refs/heads/main/docs/examples/policies/sbom/cyclonedx-licenses.yaml
