# This is an example contract that expects a container, an SBOM, and a vulnerabilities report.
apiVersion: chainloop.dev/v1
kind: Contract
metadata:
  name: quickstart-contract-oss
  description: Example contract with container, SBOM, and vulnerabilities report for OSS
spec:
  materials:
    - name: container
      type: CONTAINER_IMAGE
    - name: sbom
      type: SBOM_CYCLONEDX_JSON
      optional: true
    - name: vulnerabilities-report
      type: SARIF
      optional: true

  policies:
    attestation:
      - ref: https://raw.githubusercontent.com/chainloop-dev/chainloop/refs/heads/main/docs/examples/policies/chainloop-commit.yaml
      - ref: https://raw.githubusercontent.com/chainloop-dev/chainloop/refs/heads/main/docs/examples/policies/sbom/sbom-present.yaml
    materials:
      - ref: https://raw.githubusercontent.com/chainloop-dev/chainloop/refs/heads/main/docs/examples/policies/sbom/cyclonedx-licenses.yaml

