// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/chainloop-dev/chainloop/app/controlplane/internal/biz"
	"github.com/chainloop-dev/chainloop/app/controlplane/internal/conf"
	"github.com/chainloop-dev/chainloop/app/controlplane/internal/data"
	"github.com/chainloop-dev/chainloop/app/controlplane/internal/server"
	"github.com/chainloop-dev/chainloop/app/controlplane/internal/service"
	"github.com/chainloop-dev/chainloop/internal/blobmanager/oci"
	"github.com/chainloop-dev/chainloop/internal/credentials"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, auth *conf.Auth, confData *conf.Data, readerWriter credentials.ReaderWriter, logger log.Logger) (*app, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData, logger)
	membershipRepo := data.NewMembershipRepo(dataData, logger)
	membershipUseCase := biz.NewMembershipUsecase(membershipRepo, logger)
	organizationRepo := data.NewOrganizationRepo(dataData, logger)
	ociRepositoryRepo := data.NewOCIRepositoryRepo(dataData, logger)
	backendProvider := oci.NewBackendProvider(readerWriter)
	ociRepositoryUseCase := biz.NewOCIRepositoryUsecase(ociRepositoryRepo, readerWriter, backendProvider, logger)
	integrationRepo := data.NewIntegrationRepo(dataData, logger)
	integrationAttachmentRepo := data.NewIntegrationAttachmentRepo(dataData, logger)
	workflowRepo := data.NewWorkflowRepo(dataData, logger)
	newIntegrationUsecaseOpts := &biz.NewIntegrationUsecaseOpts{
		IRepo:   integrationRepo,
		IaRepo:  integrationAttachmentRepo,
		WfRepo:  workflowRepo,
		CredsRW: readerWriter,
		Logger:  logger,
	}
	integrationUseCase := biz.NewIntegrationUsecase(newIntegrationUsecaseOpts)
	organizationUseCase := biz.NewOrganizationUsecase(organizationRepo, ociRepositoryUseCase, integrationUseCase, logger)
	newUserUseCaseParams := &biz.NewUserUseCaseParams{
		UserRepo:            userRepo,
		MembershipUseCase:   membershipUseCase,
		OrganizationUseCase: organizationUseCase,
		Logger:              logger,
	}
	userUseCase := biz.NewUserUseCase(newUserUseCaseParams)
	robotAccountRepo := data.NewRobotAccountRepo(dataData, logger)
	robotAccountUseCase := biz.NewRootAccountUseCase(robotAccountRepo, workflowRepo, auth, logger)
	workflowContractRepo := data.NewWorkflowContractRepo(dataData, logger)
	workflowContractUseCase := biz.NewWorkflowContractUsecase(workflowContractRepo, logger)
	workflowUseCase := biz.NewWorkflowUsecase(workflowRepo, workflowContractUseCase, logger)
	v := serviceOpts(logger)
	workflowService := service.NewWorkflowService(workflowUseCase, v...)
	authService, err := service.NewAuthService(userUseCase, organizationUseCase, membershipUseCase, auth, confServer, v...)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	robotAccountService := service.NewRobotAccountService(robotAccountUseCase, v...)
	workflowRunRepo := data.NewWorkflowRunRepo(dataData, logger)
	workflowRunUseCase, err := biz.NewWorkflowRunUsecase(workflowRunRepo, workflowRepo, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	attestationUseCase := biz.NewAttestationUseCase(logger)
	newWorkflowRunServiceOpts := &service.NewWorkflowRunServiceOpts{
		WorkflowRunUC:      workflowRunUseCase,
		WorkflowUC:         workflowUseCase,
		AttestationUC:      attestationUseCase,
		WorkflowContractUC: workflowContractUseCase,
		CredsReader:        readerWriter,
		Opts:               v,
	}
	workflowRunService := service.NewWorkflowRunService(newWorkflowRunServiceOpts)
	casCredentialsUseCase, err := biz.NewCASCredentialsUseCase(auth, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	newAttestationServiceOpts := &service.NewAttestationServiceOpts{
		WorkflowRunUC:      workflowRunUseCase,
		WorkflowUC:         workflowUseCase,
		WorkflowContractUC: workflowContractUseCase,
		OCIUC:              ociRepositoryUseCase,
		AttestationUC:      attestationUseCase,
		CredsReader:        readerWriter,
		IntegrationUseCase: integrationUseCase,
		CasCredsUseCase:    casCredentialsUseCase,
		Opts:               v,
	}
	attestationService := service.NewAttestationService(newAttestationServiceOpts)
	workflowContractService := service.NewWorkflowSchemaService(workflowContractUseCase, v...)
	contextService := service.NewContextService(ociRepositoryUseCase, v...)
	casCredentialsService := service.NewCASCredentialsService(casCredentialsUseCase, ociRepositoryUseCase, v...)
	orgMetricsRepo := data.NewOrgMetricsRepo(dataData, logger)
	orgMetricsUseCase, err := biz.NewOrgMetricsUseCase(orgMetricsRepo, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	orgMetricsService := service.NewOrgMetricsService(orgMetricsUseCase, v...)
	ociRepositoryService := service.NewOCIRepositoryService(ociRepositoryUseCase, v...)
	integrationsService := service.NewIntegrationsService(integrationUseCase, workflowUseCase, v...)
	organizationService := service.NewOrganizationService(membershipUseCase, v...)
	opts := &server.Opts{
		UserUseCase:          userUseCase,
		RobotAccountUseCase:  robotAccountUseCase,
		OCIRepositoryUseCase: ociRepositoryUseCase,
		WorkflowSvc:          workflowService,
		AuthSvc:              authService,
		RobotAccountSvc:      robotAccountService,
		WorkflowRunSvc:       workflowRunService,
		AttesstationSvc:      attestationService,
		WorkflowContractSvc:  workflowContractService,
		ContextSvc:           contextService,
		CASCredsSvc:          casCredentialsService,
		OrgMetricsSvc:        orgMetricsService,
		OCIRepositorySvc:     ociRepositoryService,
		IntegrationsSvc:      integrationsService,
		OrganizationSvc:      organizationService,
		Logger:               logger,
		ServerConfig:         confServer,
		AuthConfig:           auth,
	}
	grpcServer := server.NewGRPCServer(opts)
	httpServer, err := server.NewHTTPServer(opts, grpcServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	httpMetricsServer, err := server.NewHTTPMetricsServer(opts)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	workflowRunExpirerUseCase := biz.NewWorkflowRunExpirerUseCase(workflowRunRepo, logger)
	mainApp := newApp(logger, grpcServer, httpServer, httpMetricsServer, workflowRunExpirerUseCase)
	return mainApp, func() {
		cleanup()
	}, nil
}

// wire.go:

func serviceOpts(l log.Logger) []service.NewOpt {
	return []service.NewOpt{service.WithLogger(l)}
}
