# Require both a container image reference and a CycloneDX SBOM with the attestation happening in GitHub actions
apiVersion: chainloop.dev/v1
kind: Contract
metadata:
  name: github
  description: Require both a container image reference and a CycloneDX SBOM with the attestation happening in GitHub actions
spec:
  materials:
    - type: CONTAINER_IMAGE
      name: image
      output: true

    - type: SBOM_CYCLONEDX_JSON
      name: sbom

  runner:
    type: "GITHUB_ACTION"
