// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: jsonfilter/v1/jsonfilter.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// JSONOperator represents supported JSON filter operators.
type JSONOperator int32

const (
	JSONOperator_JSON_OPERATOR_UNSPECIFIED JSONOperator = 0
	JSONOperator_JSON_OPERATOR_EQ          JSONOperator = 1
	JSONOperator_JSON_OPERATOR_NEQ         JSONOperator = 2
	JSONOperator_JSON_OPERATOR_IN          JSONOperator = 3
)

// Enum value maps for JSONOperator.
var (
	JSONOperator_name = map[int32]string{
		0: "JSON_OPERATOR_UNSPECIFIED",
		1: "JSON_OPERATOR_EQ",
		2: "JSON_OPERATOR_NEQ",
		3: "JSON_OPERATOR_IN",
	}
	JSONOperator_value = map[string]int32{
		"JSON_OPERATOR_UNSPECIFIED": 0,
		"JSON_OPERATOR_EQ":          1,
		"JSON_OPERATOR_NEQ":         2,
		"JSON_OPERATOR_IN":          3,
	}
)

func (x JSONOperator) Enum() *JSONOperator {
	p := new(JSONOperator)
	*p = x
	return p
}

func (x JSONOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JSONOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_jsonfilter_v1_jsonfilter_proto_enumTypes[0].Descriptor()
}

func (JSONOperator) Type() protoreflect.EnumType {
	return &file_jsonfilter_v1_jsonfilter_proto_enumTypes[0]
}

func (x JSONOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JSONOperator.Descriptor instead.
func (JSONOperator) EnumDescriptor() ([]byte, []int) {
	return file_jsonfilter_v1_jsonfilter_proto_rawDescGZIP(), []int{0}
}

// JSONFilter represents a filter for JSON fields.
type JSONFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FieldPath     string                 `protobuf:"bytes,1,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	Operator      JSONOperator           `protobuf:"varint,2,opt,name=operator,proto3,enum=jsonfilter.v1.JSONOperator" json:"operator,omitempty"`
	Value         *string                `protobuf:"bytes,43,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSONFilter) Reset() {
	*x = JSONFilter{}
	mi := &file_jsonfilter_v1_jsonfilter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSONFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSONFilter) ProtoMessage() {}

func (x *JSONFilter) ProtoReflect() protoreflect.Message {
	mi := &file_jsonfilter_v1_jsonfilter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSONFilter.ProtoReflect.Descriptor instead.
func (*JSONFilter) Descriptor() ([]byte, []int) {
	return file_jsonfilter_v1_jsonfilter_proto_rawDescGZIP(), []int{0}
}

func (x *JSONFilter) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *JSONFilter) GetOperator() JSONOperator {
	if x != nil {
		return x.Operator
	}
	return JSONOperator_JSON_OPERATOR_UNSPECIFIED
}

func (x *JSONFilter) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

var File_jsonfilter_v1_jsonfilter_proto protoreflect.FileDescriptor

const file_jsonfilter_v1_jsonfilter_proto_rawDesc = "" +
	"\n" +
	"\x1ejsonfilter/v1/jsonfilter.proto\x12\rjsonfilter.v1\x1a\x1bbuf/validate/validate.proto\"\x9c\x01\n" +
	"\n" +
	"JSONFilter\x12&\n" +
	"\n" +
	"field_path\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tfieldPath\x12A\n" +
	"\boperator\x18\x02 \x01(\x0e2\x1b.jsonfilter.v1.JSONOperatorB\b\xbaH\x05\x82\x01\x02\x10\x01R\boperator\x12\x19\n" +
	"\x05value\x18+ \x01(\tH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value*p\n" +
	"\fJSONOperator\x12\x1d\n" +
	"\x19JSON_OPERATOR_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10JSON_OPERATOR_EQ\x10\x01\x12\x15\n" +
	"\x11JSON_OPERATOR_NEQ\x10\x02\x12\x14\n" +
	"\x10JSON_OPERATOR_IN\x10\x03BGZEgithub.com/chainloop-dev/chainloop/app/controlplane/api/jsonfilter/v1b\x06proto3"

var (
	file_jsonfilter_v1_jsonfilter_proto_rawDescOnce sync.Once
	file_jsonfilter_v1_jsonfilter_proto_rawDescData []byte
)

func file_jsonfilter_v1_jsonfilter_proto_rawDescGZIP() []byte {
	file_jsonfilter_v1_jsonfilter_proto_rawDescOnce.Do(func() {
		file_jsonfilter_v1_jsonfilter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_jsonfilter_v1_jsonfilter_proto_rawDesc), len(file_jsonfilter_v1_jsonfilter_proto_rawDesc)))
	})
	return file_jsonfilter_v1_jsonfilter_proto_rawDescData
}

var file_jsonfilter_v1_jsonfilter_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_jsonfilter_v1_jsonfilter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_jsonfilter_v1_jsonfilter_proto_goTypes = []any{
	(JSONOperator)(0),  // 0: jsonfilter.v1.JSONOperator
	(*JSONFilter)(nil), // 1: jsonfilter.v1.JSONFilter
}
var file_jsonfilter_v1_jsonfilter_proto_depIdxs = []int32{
	0, // 0: jsonfilter.v1.JSONFilter.operator:type_name -> jsonfilter.v1.JSONOperator
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_jsonfilter_v1_jsonfilter_proto_init() }
func file_jsonfilter_v1_jsonfilter_proto_init() {
	if File_jsonfilter_v1_jsonfilter_proto != nil {
		return
	}
	file_jsonfilter_v1_jsonfilter_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_jsonfilter_v1_jsonfilter_proto_rawDesc), len(file_jsonfilter_v1_jsonfilter_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_jsonfilter_v1_jsonfilter_proto_goTypes,
		DependencyIndexes: file_jsonfilter_v1_jsonfilter_proto_depIdxs,
		EnumInfos:         file_jsonfilter_v1_jsonfilter_proto_enumTypes,
		MessageInfos:      file_jsonfilter_v1_jsonfilter_proto_msgTypes,
	}.Build()
	File_jsonfilter_v1_jsonfilter_proto = out.File
	file_jsonfilter_v1_jsonfilter_proto_goTypes = nil
	file_jsonfilter_v1_jsonfilter_proto_depIdxs = nil
}
