# based from https://github.com/spacelift-io/spacelift-policies-example-library/blob/main/.regal/config.yaml
# Default config
rules:
  idiomatic:
    directory-package-mismatch:
      level: ignore
    no-defined-entrypoint:
      level: warning
  style:
    todo-comment:
      level: ignore
    line-length:
      level: ignore
    rule-length:
      level: ignore