{{- /*
Copyright Chainloop, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chainloop.dex.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: dex
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    issuer: http://{{ include "chainloop.dex" . }}:5556/dex

    storage:
      type: memory

    web:
      http: 0.0.0.0:5556

    staticClients:
      - id: chainloop-dev
        name: "Chainloop Dev"
        redirectURIs:
          - "http://0.0.0.0:8000/auth/callback"
          - "http://localhost:8000/auth/callback"
          {{ $controlPlaneUrl := include "chainloop.controlplane.external_url" . }}
          {{- if not (eq $controlPlaneUrl "null") -}}
          - "{{ $controlPlaneUrl }}/auth/callback"
          {{- end -}}
        secret: ZXhhbXBsZS1hcHAtc2VjcmV0

    # required to enable static passwords
    enablePasswordDB: true

    staticPasswords:
      - email: "john@chainloop.local"
        # password: "password"
        hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
      - email: "sarah@chainloop.local"
        # password: "password"
        hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
