apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chainloop.cas.fullname" . }}
  labels:
    {{- include "chainloop.cas.labels" . | nindent 4 }}
data:
  server.yaml: |
    server:
      http:
        addr: 0.0.0.0:8000
        timeout: 1s
      grpc:
        addr: 0.0.0.0:9000
        timeout: 1s
      http_metrics:
        addr: 0.0.0.0:5000