apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chainloop.cas.fullname" . }}
  labels:
    {{- include "chainloop.cas.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.secret.yaml: |
    credentials_service: {{- include "chainloop.credentials_service_settings" . | indent 6 }}
    auth:
      robot_account_public_key_path: "/tmp/cas.public.pem"
    # TODO: add observability