apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chainloop.cas.fullname" . }}
  labels:
    {{- include "chainloop.cas.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if and .Values.sentry .Values.sentry.enabled }}
  config.observability.yaml: |
    observability:
      sentry:
        dsn: {{ required "Sentry DSN required" .Values.sentry.dsn | quote }}
        environment: {{ required "Sentry environment required" .Values.sentry.environment | quote }}
  {{- end }}
  config.secret.yaml: |
    credentials_service: {{- include "chainloop.credentials_service_settings" . | indent 6 }}
    auth:
      public_key_path: "/tmp/cas.public.pem"
    # TODO: add observability