apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chainloop.cas.fullname" . }}-jwt-public-key
  labels:
    {{- include "chainloop.cas.labels" . | nindent 4 }}
type: Opaque
data:
  cas.public.pem: {{ include "chainloop.casjwt.public_key" . | b64enc | quote  }}