apiVersion: v1
kind: Service
metadata:
  name: {{ include "chainloop.cas.fullname" . }}
  labels:
    {{- include "chainloop.cas.labels" . | nindent 4 }}
  {{- with .Values.cas.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.cas.service.type }}
  ports:
    - port: {{ .Values.cas.service.port }}
      targetPort: {{ .Values.cas.service.targetPort }}
      protocol: TCP
      name: http
      nodePort: {{ include "chainloop.node_port" .Values.cas.service }}
  selector: {{- include "chainloop.cas.selectorLabels" . | nindent 4 }}
