{{- if .Values.cas.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chainloop.cas.serviceAccountName" . }}
  labels:
    {{- include "chainloop.cas.labels" . | nindent 4 }}
  {{- with .Values.cas.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
