apiVersion: v1
kind: Service
metadata:
  name: {{ include "chainloop.cas.fullname" . }}-api
  labels:
    {{- include "chainloop.cas.labels" . | nindent 4 }}
  {{- with .Values.cas.serviceAPI.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.cas.serviceAPI.type }}
  ports:
    - port: {{ .Values.cas.serviceAPI.port }}
      targetPort: {{ .Values.cas.serviceAPI.targetPort }}
      protocol: TCP
      name: grpc
      nodePort: {{ include "chainloop.node_port" .Values.cas.serviceAPI }}
  selector:
    {{- include "chainloop.cas.selectorLabels" . | nindent 4 }}
