// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/chainloop-dev/chainloop/pkg/attestation/crafter"
	mock "github.com/stretchr/testify/mock"
)

// NewStateManager creates a new instance of StateManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateManager {
	mock := &StateManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StateManager is an autogenerated mock type for the StateManager type
type StateManager struct {
	mock.Mock
}

type StateManager_Expecter struct {
	mock *mock.Mock
}

func (_m *StateManager) EXPECT() *StateManager_Expecter {
	return &StateManager_Expecter{mock: &_m.Mock}
}

// Info provides a mock function for the type StateManager
func (_mock *StateManager) Info(ctx context.Context, key string) string {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// StateManager_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type StateManager_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *StateManager_Expecter) Info(ctx interface{}, key interface{}) *StateManager_Info_Call {
	return &StateManager_Info_Call{Call: _e.mock.On("Info", ctx, key)}
}

func (_c *StateManager_Info_Call) Run(run func(ctx context.Context, key string)) *StateManager_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateManager_Info_Call) Return(s string) *StateManager_Info_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *StateManager_Info_Call) RunAndReturn(run func(ctx context.Context, key string) string) *StateManager_Info_Call {
	_c.Call.Return(run)
	return _c
}

// Initialized provides a mock function for the type StateManager
func (_mock *StateManager) Initialized(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Initialized")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// StateManager_Initialized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Initialized'
type StateManager_Initialized_Call struct {
	*mock.Call
}

// Initialized is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *StateManager_Expecter) Initialized(ctx interface{}, key interface{}) *StateManager_Initialized_Call {
	return &StateManager_Initialized_Call{Call: _e.mock.On("Initialized", ctx, key)}
}

func (_c *StateManager_Initialized_Call) Run(run func(ctx context.Context, key string)) *StateManager_Initialized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateManager_Initialized_Call) Return(b bool, err error) *StateManager_Initialized_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *StateManager_Initialized_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *StateManager_Initialized_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type StateManager
func (_mock *StateManager) Read(ctx context.Context, key string, state *crafter.VersionedCraftingState) error {
	ret := _mock.Called(ctx, key, state)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *crafter.VersionedCraftingState) error); ok {
		r0 = returnFunc(ctx, key, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateManager_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type StateManager_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - state *crafter.VersionedCraftingState
func (_e *StateManager_Expecter) Read(ctx interface{}, key interface{}, state interface{}) *StateManager_Read_Call {
	return &StateManager_Read_Call{Call: _e.mock.On("Read", ctx, key, state)}
}

func (_c *StateManager_Read_Call) Run(run func(ctx context.Context, key string, state *crafter.VersionedCraftingState)) *StateManager_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *crafter.VersionedCraftingState
		if args[2] != nil {
			arg2 = args[2].(*crafter.VersionedCraftingState)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StateManager_Read_Call) Return(err error) *StateManager_Read_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateManager_Read_Call) RunAndReturn(run func(ctx context.Context, key string, state *crafter.VersionedCraftingState) error) *StateManager_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type StateManager
func (_mock *StateManager) Reset(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateManager_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type StateManager_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *StateManager_Expecter) Reset(ctx interface{}, key interface{}) *StateManager_Reset_Call {
	return &StateManager_Reset_Call{Call: _e.mock.On("Reset", ctx, key)}
}

func (_c *StateManager_Reset_Call) Run(run func(ctx context.Context, key string)) *StateManager_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateManager_Reset_Call) Return(err error) *StateManager_Reset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateManager_Reset_Call) RunAndReturn(run func(ctx context.Context, key string) error) *StateManager_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function for the type StateManager
func (_mock *StateManager) Write(ctx context.Context, key string, state *crafter.VersionedCraftingState) error {
	ret := _mock.Called(ctx, key, state)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *crafter.VersionedCraftingState) error); ok {
		r0 = returnFunc(ctx, key, state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateManager_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type StateManager_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - state *crafter.VersionedCraftingState
func (_e *StateManager_Expecter) Write(ctx interface{}, key interface{}, state interface{}) *StateManager_Write_Call {
	return &StateManager_Write_Call{Call: _e.mock.On("Write", ctx, key, state)}
}

func (_c *StateManager_Write_Call) Run(run func(ctx context.Context, key string, state *crafter.VersionedCraftingState)) *StateManager_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *crafter.VersionedCraftingState
		if args[2] != nil {
			arg2 = args[2].(*crafter.VersionedCraftingState)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *StateManager_Write_Call) Return(err error) *StateManager_Write_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateManager_Write_Call) RunAndReturn(run func(ctx context.Context, key string, state *crafter.VersionedCraftingState) error) *StateManager_Write_Call {
	_c.Call.Return(run)
	return _c
}
