# Configuration file meant to be used in the development environment.
# it assumes some services are running in the host machine, like vault
# Please make sure you run those via the convenience docker compose file
# [root]/devel/compose.yml
server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
  http_metrics:
    addr: 0.0.0.0:5001

credentials_service:
  # Remember to run vault via docker compose up
  vault:
    address: ${VAULT_ADDRESS:http://0.0.0.0:8200}
    token: ${VAULT_TOKEN:notasecret}

auth:
  robot_account_public_key_path: "../../devel/devkeys/cas.pub"
