# Copyright Chainloop, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

apiVersion: v2
name: dex
description: Dex is an identity service that uses OpenID Connect to drive authentication for other apps.

type: application
# Bump the patch (not minor, not major) version on each change in the Chart Source code
version: 0.0.1
# Do not update appVersion, this is handled automatically by the release process
appVersion: v0.0.1

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x.x

annotations:
  images: |
    - image: docker.io/bitnami/dex:2.40.0-debian-12-r1
      name: dex