FROM golang:1.24@sha256:991aa6a6e4431f2f01e869a812934bd60fbc87fb939e4a1ea54b8494ab9d2fc6 AS builder

FROM scratch

COPY ./artifact-cas /
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

USER 1001

ENTRYPOINT [ "/artifact-cas", "--conf", "/data/conf"]
