FROM golang:1.24.4@sha256:be70d93633d07a2acae4ff3401672b04f23e5850b0248d65c23e30dc75dded09 AS builder

FROM scratch

COPY ./artifact-cas /
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

USER 1001

ENTRYPOINT [ "/artifact-cas", "--conf", "/data/conf"]
