{{- /*
Copyright Chainloop, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chainloop.dex.fullname" . }}-config
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: dex
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  config.yaml: |
    issuer: http://chainloop-dex:5556/dex

    storage:
      type: memory

    web:
      http: 0.0.0.0:5556

    staticClients:
      - id: chainloop-dev
        name: "Chainloop Dev"
        secret: ZXhhbXBsZS1hcHAtc2VjcmV0
        redirectURIs:
          - "http://0.0.0.0:8000/auth/callback"
          - "http://localhost:8000/auth/callback"

    # required to enable static passwords
    enablePasswordDB: true

    staticPasswords: {{- include "common.tplvalues.render" ( dict "value" .Values.dex.staticUsers "context" $ ) | nindent 6 }}
