# Example config file
auth:
  public_key_path: "./configs/devkeys/cas.public.pem"

server:
  http:
    addr: 0.0.0.0:8001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9001
    timeout: 1s
    tls_config:
      certificate: "./configs/tls/server.crt"
      private_key: "./configs/tls/server.key"
  http_metrics:
    addr: 0.0.0.0:5001

credentials_service:
  # We use the prefix to check that we can read from it on initialization
  secret_prefix: chainloop-devel
  # Remember to run vault via docker compose up
  vault:
    address: ${VAULT_ADDRESS:http://0.0.0.0:8200}
    token: ${VAULT_TOKEN:notasecret}

  # aws_secret_manager:
  #   creds:
  #     access_key: not-a-key
  #     secret_key: not-a-secret
  #   region: us-east-1

  # gcp_secret_manager:
  #   project_id: 522312304548
  #   auth_key: "./configs/gcp_auth_key.json"

  # azure_key_vault:
  #   tenant_id: AD-tenant-id
  #   client_id: Service Principal ID
  #   client_secret: Service Principal Secret
  #   vault_uri: https://myvault.vault.azure.net/

observability:
  sentry:
    dsn: "http://sentryDomain"
    environment: development # production