// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	biz "github.com/chainloop-dev/chainloop/app/controlplane/pkg/biz"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MembershipsRBAC is an autogenerated mock type for the MembershipsRBAC type
type MembershipsRBAC struct {
	mock.Mock
}

// ListAllMembershipsForUser provides a mock function with given fields: ctx, userID
func (_m *MembershipsRBAC) ListAllMembershipsForUser(ctx context.Context, userID uuid.UUID) ([]*biz.Membership, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListAllMembershipsForUser")
	}

	var r0 []*biz.Membership
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*biz.Membership, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*biz.Membership); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*biz.Membership)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMembershipsRBAC creates a new instance of MembershipsRBAC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMembershipsRBAC(t interface {
	mock.TestingT
	Cleanup(func())
}) *MembershipsRBAC {
	mock := &MembershipsRBAC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
