// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: controlplane/v1/cas_backends.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CASBackendServiceListRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CASBackendServiceListRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CASBackendServiceListRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CASBackendServiceListRequestMultiError, or nil if none found.
func (m *CASBackendServiceListRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CASBackendServiceListRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return CASBackendServiceListRequestMultiError(errors)
	}

	return nil
}

// CASBackendServiceListRequestMultiError is an error wrapping multiple
// validation errors returned by CASBackendServiceListRequest.ValidateAll() if
// the designated constraints aren't met.
type CASBackendServiceListRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CASBackendServiceListRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CASBackendServiceListRequestMultiError) AllErrors() []error { return m }

// CASBackendServiceListRequestValidationError is the validation error returned
// by CASBackendServiceListRequest.Validate if the designated constraints
// aren't met.
type CASBackendServiceListRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CASBackendServiceListRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CASBackendServiceListRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CASBackendServiceListRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CASBackendServiceListRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CASBackendServiceListRequestValidationError) ErrorName() string {
	return "CASBackendServiceListRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CASBackendServiceListRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCASBackendServiceListRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CASBackendServiceListRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CASBackendServiceListRequestValidationError{}

// Validate checks the field values on CASBackendServiceListResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CASBackendServiceListResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CASBackendServiceListResponse with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// CASBackendServiceListResponseMultiError, or nil if none found.
func (m *CASBackendServiceListResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CASBackendServiceListResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetResult() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, CASBackendServiceListResponseValidationError{
						field:  fmt.Sprintf("Result[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, CASBackendServiceListResponseValidationError{
						field:  fmt.Sprintf("Result[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return CASBackendServiceListResponseValidationError{
					field:  fmt.Sprintf("Result[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return CASBackendServiceListResponseMultiError(errors)
	}

	return nil
}

// CASBackendServiceListResponseMultiError is an error wrapping multiple
// validation errors returned by CASBackendServiceListResponse.ValidateAll()
// if the designated constraints aren't met.
type CASBackendServiceListResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CASBackendServiceListResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CASBackendServiceListResponseMultiError) AllErrors() []error { return m }

// CASBackendServiceListResponseValidationError is the validation error
// returned by CASBackendServiceListResponse.Validate if the designated
// constraints aren't met.
type CASBackendServiceListResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CASBackendServiceListResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CASBackendServiceListResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CASBackendServiceListResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CASBackendServiceListResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CASBackendServiceListResponseValidationError) ErrorName() string {
	return "CASBackendServiceListResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CASBackendServiceListResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCASBackendServiceListResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CASBackendServiceListResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CASBackendServiceListResponseValidationError{}
