//
// Copyright 2024-2025 The Chainloop Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: controlplane/v1/cas_backends.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/go-kratos/kratos/v2/errors"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CASBackendErrorReason int32

const (
	CASBackendErrorReason_CAS_BACKEND_ERROR_REASON_UNSPECIFIED CASBackendErrorReason = 0
	CASBackendErrorReason_CAS_BACKEND_ERROR_REASON_REQUIRED    CASBackendErrorReason = 1
	// The repository does not seem to be operational
	// a previous validation has failed
	CASBackendErrorReason_CAS_BACKEND_ERROR_REASON_INVALID CASBackendErrorReason = 2
)

// Enum value maps for CASBackendErrorReason.
var (
	CASBackendErrorReason_name = map[int32]string{
		0: "CAS_BACKEND_ERROR_REASON_UNSPECIFIED",
		1: "CAS_BACKEND_ERROR_REASON_REQUIRED",
		2: "CAS_BACKEND_ERROR_REASON_INVALID",
	}
	CASBackendErrorReason_value = map[string]int32{
		"CAS_BACKEND_ERROR_REASON_UNSPECIFIED": 0,
		"CAS_BACKEND_ERROR_REASON_REQUIRED":    1,
		"CAS_BACKEND_ERROR_REASON_INVALID":     2,
	}
)

func (x CASBackendErrorReason) Enum() *CASBackendErrorReason {
	p := new(CASBackendErrorReason)
	*p = x
	return p
}

func (x CASBackendErrorReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CASBackendErrorReason) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_v1_cas_backends_proto_enumTypes[0].Descriptor()
}

func (CASBackendErrorReason) Type() protoreflect.EnumType {
	return &file_controlplane_v1_cas_backends_proto_enumTypes[0]
}

func (x CASBackendErrorReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CASBackendErrorReason.Descriptor instead.
func (CASBackendErrorReason) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_v1_cas_backends_proto_rawDescGZIP(), []int{0}
}

type CASBackendServiceListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASBackendServiceListRequest) Reset() {
	*x = CASBackendServiceListRequest{}
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASBackendServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASBackendServiceListRequest) ProtoMessage() {}

func (x *CASBackendServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASBackendServiceListRequest.ProtoReflect.Descriptor instead.
func (*CASBackendServiceListRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_cas_backends_proto_rawDescGZIP(), []int{0}
}

type CASBackendServiceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*CASBackendItem      `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASBackendServiceListResponse) Reset() {
	*x = CASBackendServiceListResponse{}
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASBackendServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASBackendServiceListResponse) ProtoMessage() {}

func (x *CASBackendServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASBackendServiceListResponse.ProtoReflect.Descriptor instead.
func (*CASBackendServiceListResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_cas_backends_proto_rawDescGZIP(), []int{1}
}

func (x *CASBackendServiceListResponse) GetResult() []*CASBackendItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type CASBackendServiceCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Location, e.g. bucket name, OCI bucket name, ...
	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	// Type of the backend, OCI, S3, ...
	Provider string `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	// Descriptive name
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Set as default in your organization
	Default bool `protobuf:"varint,4,opt,name=default,proto3" json:"default,omitempty"`
	// Arbitrary configuration for the integration
	Credentials *structpb.Struct `protobuf:"bytes,5,opt,name=credentials,proto3" json:"credentials,omitempty"`
	Name        string           `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	// Maximum size in bytes for each blob stored in this backend.
	// If not specified, defaults to the system default (typically 100MB).
	MaxBytes      *int64 `protobuf:"varint,7,opt,name=max_bytes,json=maxBytes,proto3,oneof" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASBackendServiceCreateRequest) Reset() {
	*x = CASBackendServiceCreateRequest{}
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASBackendServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASBackendServiceCreateRequest) ProtoMessage() {}

func (x *CASBackendServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASBackendServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*CASBackendServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_cas_backends_proto_rawDescGZIP(), []int{2}
}

func (x *CASBackendServiceCreateRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CASBackendServiceCreateRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *CASBackendServiceCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CASBackendServiceCreateRequest) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

func (x *CASBackendServiceCreateRequest) GetCredentials() *structpb.Struct {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *CASBackendServiceCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CASBackendServiceCreateRequest) GetMaxBytes() int64 {
	if x != nil && x.MaxBytes != nil {
		return *x.MaxBytes
	}
	return 0
}

type CASBackendServiceCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *CASBackendItem        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASBackendServiceCreateResponse) Reset() {
	*x = CASBackendServiceCreateResponse{}
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASBackendServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASBackendServiceCreateResponse) ProtoMessage() {}

func (x *CASBackendServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASBackendServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*CASBackendServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_cas_backends_proto_rawDescGZIP(), []int{3}
}

func (x *CASBackendServiceCreateResponse) GetResult() *CASBackendItem {
	if x != nil {
		return x.Result
	}
	return nil
}

// Update a CAS backend is limited to
// - description
// - set is as default
// - rotate credentials
// - max blob size
type CASBackendServiceUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Description
	Description *string `protobuf:"bytes,2,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// Set as default in your organization
	Default *bool `protobuf:"varint,3,opt,name=default,proto3,oneof" json:"default,omitempty"`
	// Credentials, useful for rotation
	Credentials *structpb.Struct `protobuf:"bytes,4,opt,name=credentials,proto3" json:"credentials,omitempty"`
	// Maximum size in bytes for each blob stored in this backend.
	MaxBytes      *int64 `protobuf:"varint,5,opt,name=max_bytes,json=maxBytes,proto3,oneof" json:"max_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASBackendServiceUpdateRequest) Reset() {
	*x = CASBackendServiceUpdateRequest{}
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASBackendServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASBackendServiceUpdateRequest) ProtoMessage() {}

func (x *CASBackendServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASBackendServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*CASBackendServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_cas_backends_proto_rawDescGZIP(), []int{4}
}

func (x *CASBackendServiceUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CASBackendServiceUpdateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CASBackendServiceUpdateRequest) GetDefault() bool {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return false
}

func (x *CASBackendServiceUpdateRequest) GetCredentials() *structpb.Struct {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *CASBackendServiceUpdateRequest) GetMaxBytes() int64 {
	if x != nil && x.MaxBytes != nil {
		return *x.MaxBytes
	}
	return 0
}

type CASBackendServiceUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *CASBackendItem        `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASBackendServiceUpdateResponse) Reset() {
	*x = CASBackendServiceUpdateResponse{}
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASBackendServiceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASBackendServiceUpdateResponse) ProtoMessage() {}

func (x *CASBackendServiceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASBackendServiceUpdateResponse.ProtoReflect.Descriptor instead.
func (*CASBackendServiceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_cas_backends_proto_rawDescGZIP(), []int{5}
}

func (x *CASBackendServiceUpdateResponse) GetResult() *CASBackendItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type CASBackendServiceDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASBackendServiceDeleteRequest) Reset() {
	*x = CASBackendServiceDeleteRequest{}
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASBackendServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASBackendServiceDeleteRequest) ProtoMessage() {}

func (x *CASBackendServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASBackendServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*CASBackendServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_cas_backends_proto_rawDescGZIP(), []int{6}
}

func (x *CASBackendServiceDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CASBackendServiceDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASBackendServiceDeleteResponse) Reset() {
	*x = CASBackendServiceDeleteResponse{}
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASBackendServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASBackendServiceDeleteResponse) ProtoMessage() {}

func (x *CASBackendServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASBackendServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*CASBackendServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_cas_backends_proto_rawDescGZIP(), []int{7}
}

type CASBackendServiceRevalidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASBackendServiceRevalidateRequest) Reset() {
	*x = CASBackendServiceRevalidateRequest{}
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASBackendServiceRevalidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASBackendServiceRevalidateRequest) ProtoMessage() {}

func (x *CASBackendServiceRevalidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASBackendServiceRevalidateRequest.ProtoReflect.Descriptor instead.
func (*CASBackendServiceRevalidateRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_cas_backends_proto_rawDescGZIP(), []int{8}
}

func (x *CASBackendServiceRevalidateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CASBackendServiceRevalidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CASBackendServiceRevalidateResponse) Reset() {
	*x = CASBackendServiceRevalidateResponse{}
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CASBackendServiceRevalidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CASBackendServiceRevalidateResponse) ProtoMessage() {}

func (x *CASBackendServiceRevalidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_cas_backends_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CASBackendServiceRevalidateResponse.ProtoReflect.Descriptor instead.
func (*CASBackendServiceRevalidateResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_cas_backends_proto_rawDescGZIP(), []int{9}
}

var File_controlplane_v1_cas_backends_proto protoreflect.FileDescriptor

const file_controlplane_v1_cas_backends_proto_rawDesc = "" +
	"\n" +
	"\"controlplane/v1/cas_backends.proto\x12\x0fcontrolplane.v1\x1a\x1bbuf/validate/validate.proto\x1a'controlplane/v1/response_messages.proto\x1a\x13errors/errors.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x1e\n" +
	"\x1cCASBackendServiceListRequest\"X\n" +
	"\x1dCASBackendServiceListResponse\x127\n" +
	"\x06result\x18\x01 \x03(\v2\x1f.controlplane.v1.CASBackendItemR\x06result\"\xb6\x02\n" +
	"\x1eCASBackendServiceCreateRequest\x12#\n" +
	"\blocation\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\blocation\x12#\n" +
	"\bprovider\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bprovider\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x18\n" +
	"\adefault\x18\x04 \x01(\bR\adefault\x12A\n" +
	"\vcredentials\x18\x05 \x01(\v2\x17.google.protobuf.StructB\x06\xbaH\x03\xc8\x01\x01R\vcredentials\x12\x1b\n" +
	"\x04name\x18\x06 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12 \n" +
	"\tmax_bytes\x18\a \x01(\x03H\x00R\bmaxBytes\x88\x01\x01B\f\n" +
	"\n" +
	"_max_bytes\"Z\n" +
	"\x1fCASBackendServiceCreateResponse\x127\n" +
	"\x06result\x18\x01 \x01(\v2\x1f.controlplane.v1.CASBackendItemR\x06result\"\x87\x03\n" +
	"\x1eCASBackendServiceUpdateRequest\x12\x97\x01\n" +
	"\x04name\x18\x01 \x01(\tB\x82\x01\xbaH\x7f\xba\x01|\n" +
	"\rname.dns-1123\x12:must contain only lowercase letters, numbers, and hyphens.\x1a/this.matches('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$')R\x04name\x12%\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x1d\n" +
	"\adefault\x18\x03 \x01(\bH\x01R\adefault\x88\x01\x01\x129\n" +
	"\vcredentials\x18\x04 \x01(\v2\x17.google.protobuf.StructR\vcredentials\x12 \n" +
	"\tmax_bytes\x18\x05 \x01(\x03H\x02R\bmaxBytes\x88\x01\x01B\x0e\n" +
	"\f_descriptionB\n" +
	"\n" +
	"\b_defaultB\f\n" +
	"\n" +
	"_max_bytes\"Z\n" +
	"\x1fCASBackendServiceUpdateResponse\x127\n" +
	"\x06result\x18\x01 \x01(\v2\x1f.controlplane.v1.CASBackendItemR\x06result\"\xba\x01\n" +
	"\x1eCASBackendServiceDeleteRequest\x12\x97\x01\n" +
	"\x04name\x18\x01 \x01(\tB\x82\x01\xbaH\x7f\xba\x01|\n" +
	"\rname.dns-1123\x12:must contain only lowercase letters, numbers, and hyphens.\x1a/this.matches('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$')R\x04name\"!\n" +
	"\x1fCASBackendServiceDeleteResponse\"\xbe\x01\n" +
	"\"CASBackendServiceRevalidateRequest\x12\x97\x01\n" +
	"\x04name\x18\x01 \x01(\tB\x82\x01\xbaH\x7f\xba\x01|\n" +
	"\rname.dns-1123\x12:must contain only lowercase letters, numbers, and hyphens.\x1a/this.matches('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$')R\x04name\"%\n" +
	"#CASBackendServiceRevalidateResponse*\xa0\x01\n" +
	"\x15CASBackendErrorReason\x12(\n" +
	"$CAS_BACKEND_ERROR_REASON_UNSPECIFIED\x10\x00\x12+\n" +
	"!CAS_BACKEND_ERROR_REASON_REQUIRED\x10\x01\x1a\x04\xa8E\x93\x03\x12*\n" +
	" CAS_BACKEND_ERROR_REASON_INVALID\x10\x02\x1a\x04\xa8E\x93\x03\x1a\x04\xa0E\xf4\x032\xba\x04\n" +
	"\x11CASBackendService\x12e\n" +
	"\x04List\x12-.controlplane.v1.CASBackendServiceListRequest\x1a..controlplane.v1.CASBackendServiceListResponse\x12k\n" +
	"\x06Create\x12/.controlplane.v1.CASBackendServiceCreateRequest\x1a0.controlplane.v1.CASBackendServiceCreateResponse\x12k\n" +
	"\x06Update\x12/.controlplane.v1.CASBackendServiceUpdateRequest\x1a0.controlplane.v1.CASBackendServiceUpdateResponse\x12k\n" +
	"\x06Delete\x12/.controlplane.v1.CASBackendServiceDeleteRequest\x1a0.controlplane.v1.CASBackendServiceDeleteResponse\x12w\n" +
	"\n" +
	"Revalidate\x123.controlplane.v1.CASBackendServiceRevalidateRequest\x1a4.controlplane.v1.CASBackendServiceRevalidateResponseBLZJgithub.com/chainloop-dev/chainloop/app/controlplane/api/controlplane/v1;v1b\x06proto3"

var (
	file_controlplane_v1_cas_backends_proto_rawDescOnce sync.Once
	file_controlplane_v1_cas_backends_proto_rawDescData []byte
)

func file_controlplane_v1_cas_backends_proto_rawDescGZIP() []byte {
	file_controlplane_v1_cas_backends_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_cas_backends_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_cas_backends_proto_rawDesc), len(file_controlplane_v1_cas_backends_proto_rawDesc)))
	})
	return file_controlplane_v1_cas_backends_proto_rawDescData
}

var file_controlplane_v1_cas_backends_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controlplane_v1_cas_backends_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_controlplane_v1_cas_backends_proto_goTypes = []any{
	(CASBackendErrorReason)(0),                  // 0: controlplane.v1.CASBackendErrorReason
	(*CASBackendServiceListRequest)(nil),        // 1: controlplane.v1.CASBackendServiceListRequest
	(*CASBackendServiceListResponse)(nil),       // 2: controlplane.v1.CASBackendServiceListResponse
	(*CASBackendServiceCreateRequest)(nil),      // 3: controlplane.v1.CASBackendServiceCreateRequest
	(*CASBackendServiceCreateResponse)(nil),     // 4: controlplane.v1.CASBackendServiceCreateResponse
	(*CASBackendServiceUpdateRequest)(nil),      // 5: controlplane.v1.CASBackendServiceUpdateRequest
	(*CASBackendServiceUpdateResponse)(nil),     // 6: controlplane.v1.CASBackendServiceUpdateResponse
	(*CASBackendServiceDeleteRequest)(nil),      // 7: controlplane.v1.CASBackendServiceDeleteRequest
	(*CASBackendServiceDeleteResponse)(nil),     // 8: controlplane.v1.CASBackendServiceDeleteResponse
	(*CASBackendServiceRevalidateRequest)(nil),  // 9: controlplane.v1.CASBackendServiceRevalidateRequest
	(*CASBackendServiceRevalidateResponse)(nil), // 10: controlplane.v1.CASBackendServiceRevalidateResponse
	(*CASBackendItem)(nil),                      // 11: controlplane.v1.CASBackendItem
	(*structpb.Struct)(nil),                     // 12: google.protobuf.Struct
}
var file_controlplane_v1_cas_backends_proto_depIdxs = []int32{
	11, // 0: controlplane.v1.CASBackendServiceListResponse.result:type_name -> controlplane.v1.CASBackendItem
	12, // 1: controlplane.v1.CASBackendServiceCreateRequest.credentials:type_name -> google.protobuf.Struct
	11, // 2: controlplane.v1.CASBackendServiceCreateResponse.result:type_name -> controlplane.v1.CASBackendItem
	12, // 3: controlplane.v1.CASBackendServiceUpdateRequest.credentials:type_name -> google.protobuf.Struct
	11, // 4: controlplane.v1.CASBackendServiceUpdateResponse.result:type_name -> controlplane.v1.CASBackendItem
	1,  // 5: controlplane.v1.CASBackendService.List:input_type -> controlplane.v1.CASBackendServiceListRequest
	3,  // 6: controlplane.v1.CASBackendService.Create:input_type -> controlplane.v1.CASBackendServiceCreateRequest
	5,  // 7: controlplane.v1.CASBackendService.Update:input_type -> controlplane.v1.CASBackendServiceUpdateRequest
	7,  // 8: controlplane.v1.CASBackendService.Delete:input_type -> controlplane.v1.CASBackendServiceDeleteRequest
	9,  // 9: controlplane.v1.CASBackendService.Revalidate:input_type -> controlplane.v1.CASBackendServiceRevalidateRequest
	2,  // 10: controlplane.v1.CASBackendService.List:output_type -> controlplane.v1.CASBackendServiceListResponse
	4,  // 11: controlplane.v1.CASBackendService.Create:output_type -> controlplane.v1.CASBackendServiceCreateResponse
	6,  // 12: controlplane.v1.CASBackendService.Update:output_type -> controlplane.v1.CASBackendServiceUpdateResponse
	8,  // 13: controlplane.v1.CASBackendService.Delete:output_type -> controlplane.v1.CASBackendServiceDeleteResponse
	10, // 14: controlplane.v1.CASBackendService.Revalidate:output_type -> controlplane.v1.CASBackendServiceRevalidateResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_controlplane_v1_cas_backends_proto_init() }
func file_controlplane_v1_cas_backends_proto_init() {
	if File_controlplane_v1_cas_backends_proto != nil {
		return
	}
	file_controlplane_v1_response_messages_proto_init()
	file_controlplane_v1_cas_backends_proto_msgTypes[2].OneofWrappers = []any{}
	file_controlplane_v1_cas_backends_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_cas_backends_proto_rawDesc), len(file_controlplane_v1_cas_backends_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_v1_cas_backends_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_cas_backends_proto_depIdxs,
		EnumInfos:         file_controlplane_v1_cas_backends_proto_enumTypes,
		MessageInfos:      file_controlplane_v1_cas_backends_proto_msgTypes,
	}.Build()
	File_controlplane_v1_cas_backends_proto = out.File
	file_controlplane_v1_cas_backends_proto_goTypes = nil
	file_controlplane_v1_cas_backends_proto_depIdxs = nil
}
