//
// Copyright 2023 The Chainloop Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: controlplane/v1/org_invite.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OrgInviteService_Create_FullMethodName = "/controlplane.v1.OrgInviteService/Create"
)

// OrgInviteServiceClient is the client API for OrgInviteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrgInviteServiceClient interface {
	// Create an invitation
	Create(ctx context.Context, in *OrgInviteServiceCreateRequest, opts ...grpc.CallOption) (*OrgInviteServiceCreateResponse, error)
}

type orgInviteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrgInviteServiceClient(cc grpc.ClientConnInterface) OrgInviteServiceClient {
	return &orgInviteServiceClient{cc}
}

func (c *orgInviteServiceClient) Create(ctx context.Context, in *OrgInviteServiceCreateRequest, opts ...grpc.CallOption) (*OrgInviteServiceCreateResponse, error) {
	out := new(OrgInviteServiceCreateResponse)
	err := c.cc.Invoke(ctx, OrgInviteService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrgInviteServiceServer is the server API for OrgInviteService service.
// All implementations must embed UnimplementedOrgInviteServiceServer
// for forward compatibility
type OrgInviteServiceServer interface {
	// Create an invitation
	Create(context.Context, *OrgInviteServiceCreateRequest) (*OrgInviteServiceCreateResponse, error)
	mustEmbedUnimplementedOrgInviteServiceServer()
}

// UnimplementedOrgInviteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrgInviteServiceServer struct {
}

func (UnimplementedOrgInviteServiceServer) Create(context.Context, *OrgInviteServiceCreateRequest) (*OrgInviteServiceCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedOrgInviteServiceServer) mustEmbedUnimplementedOrgInviteServiceServer() {}

// UnsafeOrgInviteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrgInviteServiceServer will
// result in compilation errors.
type UnsafeOrgInviteServiceServer interface {
	mustEmbedUnimplementedOrgInviteServiceServer()
}

func RegisterOrgInviteServiceServer(s grpc.ServiceRegistrar, srv OrgInviteServiceServer) {
	s.RegisterService(&OrgInviteService_ServiceDesc, srv)
}

func _OrgInviteService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrgInviteServiceCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrgInviteServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrgInviteService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrgInviteServiceServer).Create(ctx, req.(*OrgInviteServiceCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrgInviteService_ServiceDesc is the grpc.ServiceDesc for OrgInviteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrgInviteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "controlplane.v1.OrgInviteService",
	HandlerType: (*OrgInviteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _OrgInviteService_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "controlplane/v1/org_invite.proto",
}
