//
// Copyright 2024 The Chainloop Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: controlplane/v1/referrer.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReferrerServiceDiscoverPrivateRequest is the request for the DiscoverPrivate method
type ReferrerServiceDiscoverPrivateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Digest is the unique identifier of the referrer to discover
	Digest string `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	// Kind is the optional type of referrer, i.e CONTAINER_IMAGE, GIT_HEAD, ...
	// Used to filter and resolve ambiguities
	Kind          string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferrerServiceDiscoverPrivateRequest) Reset() {
	*x = ReferrerServiceDiscoverPrivateRequest{}
	mi := &file_controlplane_v1_referrer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferrerServiceDiscoverPrivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferrerServiceDiscoverPrivateRequest) ProtoMessage() {}

func (x *ReferrerServiceDiscoverPrivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_referrer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferrerServiceDiscoverPrivateRequest.ProtoReflect.Descriptor instead.
func (*ReferrerServiceDiscoverPrivateRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_referrer_proto_rawDescGZIP(), []int{0}
}

func (x *ReferrerServiceDiscoverPrivateRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ReferrerServiceDiscoverPrivateRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// DiscoverPublicSharedRequest is the request for the DiscoverPublicShared method
type DiscoverPublicSharedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Digest is the unique identifier of the referrer to discover
	Digest string `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	// Kind is the optional type of referrer, i.e CONTAINER_IMAGE, GIT_HEAD, ...
	// Used to filter and resolve ambiguities
	Kind          string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverPublicSharedRequest) Reset() {
	*x = DiscoverPublicSharedRequest{}
	mi := &file_controlplane_v1_referrer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverPublicSharedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverPublicSharedRequest) ProtoMessage() {}

func (x *DiscoverPublicSharedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_referrer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverPublicSharedRequest.ProtoReflect.Descriptor instead.
func (*DiscoverPublicSharedRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_referrer_proto_rawDescGZIP(), []int{1}
}

func (x *DiscoverPublicSharedRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *DiscoverPublicSharedRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

// DiscoverPublicSharedResponse is the response for the DiscoverPublicShared method
type DiscoverPublicSharedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result is the discovered referrer item
	Result        *ReferrerItem `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverPublicSharedResponse) Reset() {
	*x = DiscoverPublicSharedResponse{}
	mi := &file_controlplane_v1_referrer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverPublicSharedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverPublicSharedResponse) ProtoMessage() {}

func (x *DiscoverPublicSharedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_referrer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverPublicSharedResponse.ProtoReflect.Descriptor instead.
func (*DiscoverPublicSharedResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_referrer_proto_rawDescGZIP(), []int{2}
}

func (x *DiscoverPublicSharedResponse) GetResult() *ReferrerItem {
	if x != nil {
		return x.Result
	}
	return nil
}

// ReferrerServiceDiscoverPrivateResponse is the response for the DiscoverPrivate method
type ReferrerServiceDiscoverPrivateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result is the discovered referrer item
	Result        *ReferrerItem `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferrerServiceDiscoverPrivateResponse) Reset() {
	*x = ReferrerServiceDiscoverPrivateResponse{}
	mi := &file_controlplane_v1_referrer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferrerServiceDiscoverPrivateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferrerServiceDiscoverPrivateResponse) ProtoMessage() {}

func (x *ReferrerServiceDiscoverPrivateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_referrer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferrerServiceDiscoverPrivateResponse.ProtoReflect.Descriptor instead.
func (*ReferrerServiceDiscoverPrivateResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_referrer_proto_rawDescGZIP(), []int{3}
}

func (x *ReferrerServiceDiscoverPrivateResponse) GetResult() *ReferrerItem {
	if x != nil {
		return x.Result
	}
	return nil
}

// ReferrerItem represents a referrer object in the system
type ReferrerItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Digest of the referrer, i.e sha256:deadbeef or sha1:beefdead
	Digest string `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	// Kind of referrer, i.e CONTAINER_IMAGE, GIT_HEAD, ...
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Downloadable indicates whether the referrer is downloadable or not from CAS
	Downloadable bool `protobuf:"varint,3,opt,name=downloadable,proto3" json:"downloadable,omitempty"`
	// Public indicates whether the referrer is public since it belongs to a public workflow
	Public bool `protobuf:"varint,6,opt,name=public,proto3" json:"public,omitempty"`
	// References contains the list of related referrer items
	References []*ReferrerItem `protobuf:"bytes,4,rep,name=references,proto3" json:"references,omitempty"`
	// CreatedAt is the timestamp when the referrer was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Metadata contains additional descriptive information about the referrer
	Metadata map[string]string `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Annotations are key-value pairs associated with the referrer
	Annotations   map[string]string `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferrerItem) Reset() {
	*x = ReferrerItem{}
	mi := &file_controlplane_v1_referrer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferrerItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferrerItem) ProtoMessage() {}

func (x *ReferrerItem) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_referrer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferrerItem.ProtoReflect.Descriptor instead.
func (*ReferrerItem) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_referrer_proto_rawDescGZIP(), []int{4}
}

func (x *ReferrerItem) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ReferrerItem) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *ReferrerItem) GetDownloadable() bool {
	if x != nil {
		return x.Downloadable
	}
	return false
}

func (x *ReferrerItem) GetPublic() bool {
	if x != nil {
		return x.Public
	}
	return false
}

func (x *ReferrerItem) GetReferences() []*ReferrerItem {
	if x != nil {
		return x.References
	}
	return nil
}

func (x *ReferrerItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ReferrerItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ReferrerItem) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

var File_controlplane_v1_referrer_proto protoreflect.FileDescriptor

const file_controlplane_v1_referrer_proto_rawDesc = "" +
	"\n" +
	"\x1econtrolplane/v1/referrer.proto\x12\x0fcontrolplane.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xb2\x01\n" +
	"%ReferrerServiceDiscoverPrivateRequest\x12\x1f\n" +
	"\x06digest\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06digest\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind:T\x92AQ\n" +
	"O*%ReferrerServiceDiscoverPrivateRequest2&Request to discover a private referrer\"\xa4\x01\n" +
	"\x1bDiscoverPublicSharedRequest\x12\x1f\n" +
	"\x06digest\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06digest\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind:P\x92AM\n" +
	"K*\x1bDiscoverPublicSharedRequest2,Request to discover a public shared referrer\"\xa8\x01\n" +
	"\x1cDiscoverPublicSharedResponse\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.controlplane.v1.ReferrerItemR\x06result:Q\x92AN\n" +
	"L*\x1cDiscoverPublicSharedResponse2,Response for the DiscoverPublicShared method\"\xb7\x01\n" +
	"&ReferrerServiceDiscoverPrivateResponse\x125\n" +
	"\x06result\x18\x01 \x01(\v2\x1d.controlplane.v1.ReferrerItemR\x06result:V\x92AS\n" +
	"Q*&ReferrerServiceDiscoverPrivateResponse2'Response for the DiscoverPrivate method\"\xcc\x04\n" +
	"\fReferrerItem\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\"\n" +
	"\fdownloadable\x18\x03 \x01(\bR\fdownloadable\x12\x16\n" +
	"\x06public\x18\x06 \x01(\bR\x06public\x12=\n" +
	"\n" +
	"references\x18\x04 \x03(\v2\x1d.controlplane.v1.ReferrerItemR\n" +
	"references\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12G\n" +
	"\bmetadata\x18\a \x03(\v2+.controlplane.v1.ReferrerItem.MetadataEntryR\bmetadata\x12P\n" +
	"\vannotations\x18\b \x03(\v2..controlplane.v1.ReferrerItem.AnnotationsEntryR\vannotations\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01:B\x92A?\n" +
	"=*\fReferrerItem2-It represents a referrer object in the system2\xa9\x05\n" +
	"\x0fReferrerService\x12\xa9\x02\n" +
	"\x0fDiscoverPrivate\x126.controlplane.v1.ReferrerServiceDiscoverPrivateRequest\x1a7.controlplane.v1.ReferrerServiceDiscoverPrivateResponse\"\xa4\x01\x92A\x86\x01\x12\x19Discover private referrer\x1aWReturns the referrer item for a given digest in the organizations of the logged-in user:\x10application/json\x82\xd3\xe4\x93\x02\x14\x12\x12/discover/{digest}\x12\x96\x02\n" +
	"\x14DiscoverPublicShared\x12,.controlplane.v1.DiscoverPublicSharedRequest\x1a-.controlplane.v1.DiscoverPublicSharedResponse\"\xa0\x01\x92A|\x12\x1fDiscover public shared referrer\x1aGReturns the referrer item for a given digest in the public shared index:\x10application/json\x82\xd3\xe4\x93\x02\x1b\x12\x19/discover/shared/{digest}\x1aQ\x92AN\n" +
	"\x0fReferrerService\x12;Referrer service for discovering referred content by digestBLZJgithub.com/chainloop-dev/chainloop/app/controlplane/api/controlplane/v1;v1b\x06proto3"

var (
	file_controlplane_v1_referrer_proto_rawDescOnce sync.Once
	file_controlplane_v1_referrer_proto_rawDescData []byte
)

func file_controlplane_v1_referrer_proto_rawDescGZIP() []byte {
	file_controlplane_v1_referrer_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_referrer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_referrer_proto_rawDesc), len(file_controlplane_v1_referrer_proto_rawDesc)))
	})
	return file_controlplane_v1_referrer_proto_rawDescData
}

var file_controlplane_v1_referrer_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_controlplane_v1_referrer_proto_goTypes = []any{
	(*ReferrerServiceDiscoverPrivateRequest)(nil),  // 0: controlplane.v1.ReferrerServiceDiscoverPrivateRequest
	(*DiscoverPublicSharedRequest)(nil),            // 1: controlplane.v1.DiscoverPublicSharedRequest
	(*DiscoverPublicSharedResponse)(nil),           // 2: controlplane.v1.DiscoverPublicSharedResponse
	(*ReferrerServiceDiscoverPrivateResponse)(nil), // 3: controlplane.v1.ReferrerServiceDiscoverPrivateResponse
	(*ReferrerItem)(nil),                           // 4: controlplane.v1.ReferrerItem
	nil,                                            // 5: controlplane.v1.ReferrerItem.MetadataEntry
	nil,                                            // 6: controlplane.v1.ReferrerItem.AnnotationsEntry
	(*timestamppb.Timestamp)(nil),                  // 7: google.protobuf.Timestamp
}
var file_controlplane_v1_referrer_proto_depIdxs = []int32{
	4, // 0: controlplane.v1.DiscoverPublicSharedResponse.result:type_name -> controlplane.v1.ReferrerItem
	4, // 1: controlplane.v1.ReferrerServiceDiscoverPrivateResponse.result:type_name -> controlplane.v1.ReferrerItem
	4, // 2: controlplane.v1.ReferrerItem.references:type_name -> controlplane.v1.ReferrerItem
	7, // 3: controlplane.v1.ReferrerItem.created_at:type_name -> google.protobuf.Timestamp
	5, // 4: controlplane.v1.ReferrerItem.metadata:type_name -> controlplane.v1.ReferrerItem.MetadataEntry
	6, // 5: controlplane.v1.ReferrerItem.annotations:type_name -> controlplane.v1.ReferrerItem.AnnotationsEntry
	0, // 6: controlplane.v1.ReferrerService.DiscoverPrivate:input_type -> controlplane.v1.ReferrerServiceDiscoverPrivateRequest
	1, // 7: controlplane.v1.ReferrerService.DiscoverPublicShared:input_type -> controlplane.v1.DiscoverPublicSharedRequest
	3, // 8: controlplane.v1.ReferrerService.DiscoverPrivate:output_type -> controlplane.v1.ReferrerServiceDiscoverPrivateResponse
	2, // 9: controlplane.v1.ReferrerService.DiscoverPublicShared:output_type -> controlplane.v1.DiscoverPublicSharedResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_controlplane_v1_referrer_proto_init() }
func file_controlplane_v1_referrer_proto_init() {
	if File_controlplane_v1_referrer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_referrer_proto_rawDesc), len(file_controlplane_v1_referrer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_v1_referrer_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_referrer_proto_depIdxs,
		MessageInfos:      file_controlplane_v1_referrer_proto_msgTypes,
	}.Build()
	File_controlplane_v1_referrer_proto = out.File
	file_controlplane_v1_referrer_proto_goTypes = nil
	file_controlplane_v1_referrer_proto_depIdxs = nil
}
