//
// Copyright 2025 The Chainloop Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: controlplane/v1/shared_message.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProjectMemberRole defines the roles a member can have in a project
type ProjectMemberRole int32

const (
	// Default role for a project member
	ProjectMemberRole_PROJECT_MEMBER_ROLE_UNSPECIFIED ProjectMemberRole = 0
	// Admin role for a project member
	ProjectMemberRole_PROJECT_MEMBER_ROLE_ADMIN ProjectMemberRole = 1
	// Viewer role for a project member
	ProjectMemberRole_PROJECT_MEMBER_ROLE_VIEWER ProjectMemberRole = 2
)

// Enum value maps for ProjectMemberRole.
var (
	ProjectMemberRole_name = map[int32]string{
		0: "PROJECT_MEMBER_ROLE_UNSPECIFIED",
		1: "PROJECT_MEMBER_ROLE_ADMIN",
		2: "PROJECT_MEMBER_ROLE_VIEWER",
	}
	ProjectMemberRole_value = map[string]int32{
		"PROJECT_MEMBER_ROLE_UNSPECIFIED": 0,
		"PROJECT_MEMBER_ROLE_ADMIN":       1,
		"PROJECT_MEMBER_ROLE_VIEWER":      2,
	}
)

func (x ProjectMemberRole) Enum() *ProjectMemberRole {
	p := new(ProjectMemberRole)
	*p = x
	return p
}

func (x ProjectMemberRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProjectMemberRole) Descriptor() protoreflect.EnumDescriptor {
	return file_controlplane_v1_shared_message_proto_enumTypes[0].Descriptor()
}

func (ProjectMemberRole) Type() protoreflect.EnumType {
	return &file_controlplane_v1_shared_message_proto_enumTypes[0]
}

func (x ProjectMemberRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProjectMemberRole.Descriptor instead.
func (ProjectMemberRole) EnumDescriptor() ([]byte, []int) {
	return file_controlplane_v1_shared_message_proto_rawDescGZIP(), []int{0}
}

// IdentityReference represents a reference to an identity in the system.
type IdentityReference struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID is optional, but if provided, it must be a valid UUID.
	Id *string `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	// Name is optional, but if provided, it must be a non-empty string.
	Name          *string `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdentityReference) Reset() {
	*x = IdentityReference{}
	mi := &file_controlplane_v1_shared_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentityReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentityReference) ProtoMessage() {}

func (x *IdentityReference) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_shared_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentityReference.ProtoReflect.Descriptor instead.
func (*IdentityReference) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_shared_message_proto_rawDescGZIP(), []int{0}
}

func (x *IdentityReference) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *IdentityReference) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

var File_controlplane_v1_shared_message_proto protoreflect.FileDescriptor

const file_controlplane_v1_shared_message_proto_rawDesc = "" +
	"\n" +
	"$controlplane/v1/shared_message.proto\x12\x0fcontrolplane.v1\x1a\x1bbuf/validate/validate.proto\"\x88\x02\n" +
	"\x11IdentityReference\x12 \n" +
	"\x02id\x18\x01 \x01(\tB\v\xbaH\b\xd8\x01\x01r\x03\xb0\x01\x01H\x00R\x02id\x88\x01\x01\x12#\n" +
	"\x04name\x18\x02 \x01(\tB\n" +
	"\xbaH\a\xd8\x01\x01r\x02\x10\x01H\x01R\x04name\x88\x01\x01:\x9b\x01\xbaH\x97\x01\x1a\x94\x01\n" +
	"\x13id_or_name_required\x121either id or name must be provided, but not both.\x1aJ!(this.id == '' && this.name == '') && !(this.id != '' && this.name != '')B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_name*w\n" +
	"\x11ProjectMemberRole\x12#\n" +
	"\x1fPROJECT_MEMBER_ROLE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19PROJECT_MEMBER_ROLE_ADMIN\x10\x01\x12\x1e\n" +
	"\x1aPROJECT_MEMBER_ROLE_VIEWER\x10\x02BLZJgithub.com/chainloop-dev/chainloop/app/controlplane/api/controlplane/v1;v1b\x06proto3"

var (
	file_controlplane_v1_shared_message_proto_rawDescOnce sync.Once
	file_controlplane_v1_shared_message_proto_rawDescData []byte
)

func file_controlplane_v1_shared_message_proto_rawDescGZIP() []byte {
	file_controlplane_v1_shared_message_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_shared_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_shared_message_proto_rawDesc), len(file_controlplane_v1_shared_message_proto_rawDesc)))
	})
	return file_controlplane_v1_shared_message_proto_rawDescData
}

var file_controlplane_v1_shared_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_controlplane_v1_shared_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_controlplane_v1_shared_message_proto_goTypes = []any{
	(ProjectMemberRole)(0),    // 0: controlplane.v1.ProjectMemberRole
	(*IdentityReference)(nil), // 1: controlplane.v1.IdentityReference
}
var file_controlplane_v1_shared_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_controlplane_v1_shared_message_proto_init() }
func file_controlplane_v1_shared_message_proto_init() {
	if File_controlplane_v1_shared_message_proto != nil {
		return
	}
	file_controlplane_v1_shared_message_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_shared_message_proto_rawDesc), len(file_controlplane_v1_shared_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_controlplane_v1_shared_message_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_shared_message_proto_depIdxs,
		EnumInfos:         file_controlplane_v1_shared_message_proto_enumTypes,
		MessageInfos:      file_controlplane_v1_shared_message_proto_msgTypes,
	}.Build()
	File_controlplane_v1_shared_message_proto = out.File
	file_controlplane_v1_shared_message_proto_goTypes = nil
	file_controlplane_v1_shared_message_proto_depIdxs = nil
}
