//
// Copyright 2024-2025 The Chainloop Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: controlplane/v1/workflow_contract.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowContractServiceListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowContractServiceListRequest) Reset() {
	*x = WorkflowContractServiceListRequest{}
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowContractServiceListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowContractServiceListRequest) ProtoMessage() {}

func (x *WorkflowContractServiceListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowContractServiceListRequest.ProtoReflect.Descriptor instead.
func (*WorkflowContractServiceListRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_workflow_contract_proto_rawDescGZIP(), []int{0}
}

type WorkflowContractServiceListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Result        []*WorkflowContractItem `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowContractServiceListResponse) Reset() {
	*x = WorkflowContractServiceListResponse{}
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowContractServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowContractServiceListResponse) ProtoMessage() {}

func (x *WorkflowContractServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowContractServiceListResponse.ProtoReflect.Descriptor instead.
func (*WorkflowContractServiceListResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_workflow_contract_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowContractServiceListResponse) GetResult() []*WorkflowContractItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type WorkflowContractServiceCreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Raw representation of the contract in json, yaml or cue
	RawContract []byte  `protobuf:"bytes,4,opt,name=raw_contract,json=rawContract,proto3" json:"raw_contract,omitempty"`
	Description *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	// You might need to specify a project reference if you want/need to create a contract scoped to a project
	ProjectReference *IdentityReference `protobuf:"bytes,5,opt,name=project_reference,json=projectReference,proto3" json:"project_reference,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkflowContractServiceCreateRequest) Reset() {
	*x = WorkflowContractServiceCreateRequest{}
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowContractServiceCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowContractServiceCreateRequest) ProtoMessage() {}

func (x *WorkflowContractServiceCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowContractServiceCreateRequest.ProtoReflect.Descriptor instead.
func (*WorkflowContractServiceCreateRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_workflow_contract_proto_rawDescGZIP(), []int{2}
}

func (x *WorkflowContractServiceCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowContractServiceCreateRequest) GetRawContract() []byte {
	if x != nil {
		return x.RawContract
	}
	return nil
}

func (x *WorkflowContractServiceCreateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *WorkflowContractServiceCreateRequest) GetProjectReference() *IdentityReference {
	if x != nil {
		return x.ProjectReference
	}
	return nil
}

type WorkflowContractServiceCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *WorkflowContractItem  `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowContractServiceCreateResponse) Reset() {
	*x = WorkflowContractServiceCreateResponse{}
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowContractServiceCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowContractServiceCreateResponse) ProtoMessage() {}

func (x *WorkflowContractServiceCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowContractServiceCreateResponse.ProtoReflect.Descriptor instead.
func (*WorkflowContractServiceCreateResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_workflow_contract_proto_rawDescGZIP(), []int{3}
}

func (x *WorkflowContractServiceCreateResponse) GetResult() *WorkflowContractItem {
	if x != nil {
		return x.Result
	}
	return nil
}

type WorkflowContractServiceUpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Raw representation of the contract in json, yaml or cue
	RawContract   []byte  `protobuf:"bytes,5,opt,name=raw_contract,json=rawContract,proto3" json:"raw_contract,omitempty"`
	Description   *string `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowContractServiceUpdateRequest) Reset() {
	*x = WorkflowContractServiceUpdateRequest{}
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowContractServiceUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowContractServiceUpdateRequest) ProtoMessage() {}

func (x *WorkflowContractServiceUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowContractServiceUpdateRequest.ProtoReflect.Descriptor instead.
func (*WorkflowContractServiceUpdateRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_workflow_contract_proto_rawDescGZIP(), []int{4}
}

func (x *WorkflowContractServiceUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowContractServiceUpdateRequest) GetRawContract() []byte {
	if x != nil {
		return x.RawContract
	}
	return nil
}

func (x *WorkflowContractServiceUpdateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

type WorkflowContractServiceUpdateResponse struct {
	state         protoimpl.MessageState                        `protogen:"open.v1"`
	Result        *WorkflowContractServiceUpdateResponse_Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowContractServiceUpdateResponse) Reset() {
	*x = WorkflowContractServiceUpdateResponse{}
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowContractServiceUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowContractServiceUpdateResponse) ProtoMessage() {}

func (x *WorkflowContractServiceUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowContractServiceUpdateResponse.ProtoReflect.Descriptor instead.
func (*WorkflowContractServiceUpdateResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_workflow_contract_proto_rawDescGZIP(), []int{5}
}

func (x *WorkflowContractServiceUpdateResponse) GetResult() *WorkflowContractServiceUpdateResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type WorkflowContractServiceDescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Revision      int32                  `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowContractServiceDescribeRequest) Reset() {
	*x = WorkflowContractServiceDescribeRequest{}
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowContractServiceDescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowContractServiceDescribeRequest) ProtoMessage() {}

func (x *WorkflowContractServiceDescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowContractServiceDescribeRequest.ProtoReflect.Descriptor instead.
func (*WorkflowContractServiceDescribeRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_workflow_contract_proto_rawDescGZIP(), []int{6}
}

func (x *WorkflowContractServiceDescribeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowContractServiceDescribeRequest) GetRevision() int32 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type WorkflowContractServiceDescribeResponse struct {
	state         protoimpl.MessageState                          `protogen:"open.v1"`
	Result        *WorkflowContractServiceDescribeResponse_Result `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowContractServiceDescribeResponse) Reset() {
	*x = WorkflowContractServiceDescribeResponse{}
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowContractServiceDescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowContractServiceDescribeResponse) ProtoMessage() {}

func (x *WorkflowContractServiceDescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowContractServiceDescribeResponse.ProtoReflect.Descriptor instead.
func (*WorkflowContractServiceDescribeResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_workflow_contract_proto_rawDescGZIP(), []int{7}
}

func (x *WorkflowContractServiceDescribeResponse) GetResult() *WorkflowContractServiceDescribeResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

type WorkflowContractServiceDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowContractServiceDeleteRequest) Reset() {
	*x = WorkflowContractServiceDeleteRequest{}
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowContractServiceDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowContractServiceDeleteRequest) ProtoMessage() {}

func (x *WorkflowContractServiceDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowContractServiceDeleteRequest.ProtoReflect.Descriptor instead.
func (*WorkflowContractServiceDeleteRequest) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_workflow_contract_proto_rawDescGZIP(), []int{8}
}

func (x *WorkflowContractServiceDeleteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WorkflowContractServiceDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowContractServiceDeleteResponse) Reset() {
	*x = WorkflowContractServiceDeleteResponse{}
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowContractServiceDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowContractServiceDeleteResponse) ProtoMessage() {}

func (x *WorkflowContractServiceDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowContractServiceDeleteResponse.ProtoReflect.Descriptor instead.
func (*WorkflowContractServiceDeleteResponse) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_workflow_contract_proto_rawDescGZIP(), []int{9}
}

type WorkflowContractServiceUpdateResponse_Result struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Contract      *WorkflowContractItem        `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Revision      *WorkflowContractVersionItem `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowContractServiceUpdateResponse_Result) Reset() {
	*x = WorkflowContractServiceUpdateResponse_Result{}
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowContractServiceUpdateResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowContractServiceUpdateResponse_Result) ProtoMessage() {}

func (x *WorkflowContractServiceUpdateResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowContractServiceUpdateResponse_Result.ProtoReflect.Descriptor instead.
func (*WorkflowContractServiceUpdateResponse_Result) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_workflow_contract_proto_rawDescGZIP(), []int{5, 0}
}

func (x *WorkflowContractServiceUpdateResponse_Result) GetContract() *WorkflowContractItem {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *WorkflowContractServiceUpdateResponse_Result) GetRevision() *WorkflowContractVersionItem {
	if x != nil {
		return x.Revision
	}
	return nil
}

type WorkflowContractServiceDescribeResponse_Result struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Contract      *WorkflowContractItem        `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Revision      *WorkflowContractVersionItem `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowContractServiceDescribeResponse_Result) Reset() {
	*x = WorkflowContractServiceDescribeResponse_Result{}
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowContractServiceDescribeResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowContractServiceDescribeResponse_Result) ProtoMessage() {}

func (x *WorkflowContractServiceDescribeResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_controlplane_v1_workflow_contract_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowContractServiceDescribeResponse_Result.ProtoReflect.Descriptor instead.
func (*WorkflowContractServiceDescribeResponse_Result) Descriptor() ([]byte, []int) {
	return file_controlplane_v1_workflow_contract_proto_rawDescGZIP(), []int{7, 0}
}

func (x *WorkflowContractServiceDescribeResponse_Result) GetContract() *WorkflowContractItem {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *WorkflowContractServiceDescribeResponse_Result) GetRevision() *WorkflowContractVersionItem {
	if x != nil {
		return x.Revision
	}
	return nil
}

var File_controlplane_v1_workflow_contract_proto protoreflect.FileDescriptor

const file_controlplane_v1_workflow_contract_proto_rawDesc = "" +
	"\n" +
	"'controlplane/v1/workflow_contract.proto\x12\x0fcontrolplane.v1\x1a\x1bbuf/validate/validate.proto\x1a'controlplane/v1/response_messages.proto\x1a$controlplane/v1/shared_message.proto\"$\n" +
	"\"WorkflowContractServiceListRequest\"d\n" +
	"#WorkflowContractServiceListResponse\x12=\n" +
	"\x06result\x18\x01 \x03(\v2%.controlplane.v1.WorkflowContractItemR\x06result\"\xef\x02\n" +
	"$WorkflowContractServiceCreateRequest\x12\x9b\x01\n" +
	"\x04name\x18\x01 \x01(\tB\x86\x01\xbaH\x82\x01\xba\x01|\n" +
	"\rname.dns-1123\x12:must contain only lowercase letters, numbers, and hyphens.\x1a/this.matches('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$')\xd8\x01\x01R\x04name\x12!\n" +
	"\fraw_contract\x18\x04 \x01(\fR\vrawContract\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12O\n" +
	"\x11project_reference\x18\x05 \x01(\v2\".controlplane.v1.IdentityReferenceR\x10projectReferenceB\x0e\n" +
	"\f_description\"f\n" +
	"%WorkflowContractServiceCreateResponse\x12=\n" +
	"\x06result\x18\x01 \x01(\v2%.controlplane.v1.WorkflowContractItemR\x06result\"\x9e\x02\n" +
	"$WorkflowContractServiceUpdateRequest\x12\x9b\x01\n" +
	"\x04name\x18\x01 \x01(\tB\x86\x01\xbaH\x82\x01\xba\x01|\n" +
	"\rname.dns-1123\x12:must contain only lowercase letters, numbers, and hyphens.\x1a/this.matches('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$')\xd8\x01\x01R\x04name\x12!\n" +
	"\fraw_contract\x18\x05 \x01(\fR\vrawContract\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x00R\vdescription\x88\x01\x01B\x0e\n" +
	"\f_description\"\x96\x02\n" +
	"%WorkflowContractServiceUpdateResponse\x12U\n" +
	"\x06result\x18\x01 \x01(\v2=.controlplane.v1.WorkflowContractServiceUpdateResponse.ResultR\x06result\x1a\x95\x01\n" +
	"\x06Result\x12A\n" +
	"\bcontract\x18\x01 \x01(\v2%.controlplane.v1.WorkflowContractItemR\bcontract\x12H\n" +
	"\brevision\x18\x02 \x01(\v2,.controlplane.v1.WorkflowContractVersionItemR\brevision\"\xde\x01\n" +
	"&WorkflowContractServiceDescribeRequest\x12\x97\x01\n" +
	"\x04name\x18\x01 \x01(\tB\x82\x01\xbaH\x7f\xba\x01|\n" +
	"\rname.dns-1123\x12:must contain only lowercase letters, numbers, and hyphens.\x1a/this.matches('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$')R\x04name\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x05R\brevision\"\x9a\x02\n" +
	"'WorkflowContractServiceDescribeResponse\x12W\n" +
	"\x06result\x18\x01 \x01(\v2?.controlplane.v1.WorkflowContractServiceDescribeResponse.ResultR\x06result\x1a\x95\x01\n" +
	"\x06Result\x12A\n" +
	"\bcontract\x18\x01 \x01(\v2%.controlplane.v1.WorkflowContractItemR\bcontract\x12H\n" +
	"\brevision\x18\x02 \x01(\v2,.controlplane.v1.WorkflowContractVersionItemR\brevision\"\xc0\x01\n" +
	"$WorkflowContractServiceDeleteRequest\x12\x97\x01\n" +
	"\x04name\x18\x01 \x01(\tB\x82\x01\xbaH\x7f\xba\x01|\n" +
	"\rname.dns-1123\x12:must contain only lowercase letters, numbers, and hyphens.\x1a/this.matches('^[a-z0-9]([-a-z0-9]*[a-z0-9])?$')R\x04name\"'\n" +
	"%WorkflowContractServiceDeleteResponse2\xf6\x04\n" +
	"\x17WorkflowContractService\x12q\n" +
	"\x04List\x123.controlplane.v1.WorkflowContractServiceListRequest\x1a4.controlplane.v1.WorkflowContractServiceListResponse\x12w\n" +
	"\x06Create\x125.controlplane.v1.WorkflowContractServiceCreateRequest\x1a6.controlplane.v1.WorkflowContractServiceCreateResponse\x12w\n" +
	"\x06Update\x125.controlplane.v1.WorkflowContractServiceUpdateRequest\x1a6.controlplane.v1.WorkflowContractServiceUpdateResponse\x12}\n" +
	"\bDescribe\x127.controlplane.v1.WorkflowContractServiceDescribeRequest\x1a8.controlplane.v1.WorkflowContractServiceDescribeResponse\x12w\n" +
	"\x06Delete\x125.controlplane.v1.WorkflowContractServiceDeleteRequest\x1a6.controlplane.v1.WorkflowContractServiceDeleteResponseBLZJgithub.com/chainloop-dev/chainloop/app/controlplane/api/controlplane/v1;v1b\x06proto3"

var (
	file_controlplane_v1_workflow_contract_proto_rawDescOnce sync.Once
	file_controlplane_v1_workflow_contract_proto_rawDescData []byte
)

func file_controlplane_v1_workflow_contract_proto_rawDescGZIP() []byte {
	file_controlplane_v1_workflow_contract_proto_rawDescOnce.Do(func() {
		file_controlplane_v1_workflow_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_controlplane_v1_workflow_contract_proto_rawDesc), len(file_controlplane_v1_workflow_contract_proto_rawDesc)))
	})
	return file_controlplane_v1_workflow_contract_proto_rawDescData
}

var file_controlplane_v1_workflow_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_controlplane_v1_workflow_contract_proto_goTypes = []any{
	(*WorkflowContractServiceListRequest)(nil),             // 0: controlplane.v1.WorkflowContractServiceListRequest
	(*WorkflowContractServiceListResponse)(nil),            // 1: controlplane.v1.WorkflowContractServiceListResponse
	(*WorkflowContractServiceCreateRequest)(nil),           // 2: controlplane.v1.WorkflowContractServiceCreateRequest
	(*WorkflowContractServiceCreateResponse)(nil),          // 3: controlplane.v1.WorkflowContractServiceCreateResponse
	(*WorkflowContractServiceUpdateRequest)(nil),           // 4: controlplane.v1.WorkflowContractServiceUpdateRequest
	(*WorkflowContractServiceUpdateResponse)(nil),          // 5: controlplane.v1.WorkflowContractServiceUpdateResponse
	(*WorkflowContractServiceDescribeRequest)(nil),         // 6: controlplane.v1.WorkflowContractServiceDescribeRequest
	(*WorkflowContractServiceDescribeResponse)(nil),        // 7: controlplane.v1.WorkflowContractServiceDescribeResponse
	(*WorkflowContractServiceDeleteRequest)(nil),           // 8: controlplane.v1.WorkflowContractServiceDeleteRequest
	(*WorkflowContractServiceDeleteResponse)(nil),          // 9: controlplane.v1.WorkflowContractServiceDeleteResponse
	(*WorkflowContractServiceUpdateResponse_Result)(nil),   // 10: controlplane.v1.WorkflowContractServiceUpdateResponse.Result
	(*WorkflowContractServiceDescribeResponse_Result)(nil), // 11: controlplane.v1.WorkflowContractServiceDescribeResponse.Result
	(*WorkflowContractItem)(nil),                           // 12: controlplane.v1.WorkflowContractItem
	(*IdentityReference)(nil),                              // 13: controlplane.v1.IdentityReference
	(*WorkflowContractVersionItem)(nil),                    // 14: controlplane.v1.WorkflowContractVersionItem
}
var file_controlplane_v1_workflow_contract_proto_depIdxs = []int32{
	12, // 0: controlplane.v1.WorkflowContractServiceListResponse.result:type_name -> controlplane.v1.WorkflowContractItem
	13, // 1: controlplane.v1.WorkflowContractServiceCreateRequest.project_reference:type_name -> controlplane.v1.IdentityReference
	12, // 2: controlplane.v1.WorkflowContractServiceCreateResponse.result:type_name -> controlplane.v1.WorkflowContractItem
	10, // 3: controlplane.v1.WorkflowContractServiceUpdateResponse.result:type_name -> controlplane.v1.WorkflowContractServiceUpdateResponse.Result
	11, // 4: controlplane.v1.WorkflowContractServiceDescribeResponse.result:type_name -> controlplane.v1.WorkflowContractServiceDescribeResponse.Result
	12, // 5: controlplane.v1.WorkflowContractServiceUpdateResponse.Result.contract:type_name -> controlplane.v1.WorkflowContractItem
	14, // 6: controlplane.v1.WorkflowContractServiceUpdateResponse.Result.revision:type_name -> controlplane.v1.WorkflowContractVersionItem
	12, // 7: controlplane.v1.WorkflowContractServiceDescribeResponse.Result.contract:type_name -> controlplane.v1.WorkflowContractItem
	14, // 8: controlplane.v1.WorkflowContractServiceDescribeResponse.Result.revision:type_name -> controlplane.v1.WorkflowContractVersionItem
	0,  // 9: controlplane.v1.WorkflowContractService.List:input_type -> controlplane.v1.WorkflowContractServiceListRequest
	2,  // 10: controlplane.v1.WorkflowContractService.Create:input_type -> controlplane.v1.WorkflowContractServiceCreateRequest
	4,  // 11: controlplane.v1.WorkflowContractService.Update:input_type -> controlplane.v1.WorkflowContractServiceUpdateRequest
	6,  // 12: controlplane.v1.WorkflowContractService.Describe:input_type -> controlplane.v1.WorkflowContractServiceDescribeRequest
	8,  // 13: controlplane.v1.WorkflowContractService.Delete:input_type -> controlplane.v1.WorkflowContractServiceDeleteRequest
	1,  // 14: controlplane.v1.WorkflowContractService.List:output_type -> controlplane.v1.WorkflowContractServiceListResponse
	3,  // 15: controlplane.v1.WorkflowContractService.Create:output_type -> controlplane.v1.WorkflowContractServiceCreateResponse
	5,  // 16: controlplane.v1.WorkflowContractService.Update:output_type -> controlplane.v1.WorkflowContractServiceUpdateResponse
	7,  // 17: controlplane.v1.WorkflowContractService.Describe:output_type -> controlplane.v1.WorkflowContractServiceDescribeResponse
	9,  // 18: controlplane.v1.WorkflowContractService.Delete:output_type -> controlplane.v1.WorkflowContractServiceDeleteResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_controlplane_v1_workflow_contract_proto_init() }
func file_controlplane_v1_workflow_contract_proto_init() {
	if File_controlplane_v1_workflow_contract_proto != nil {
		return
	}
	file_controlplane_v1_response_messages_proto_init()
	file_controlplane_v1_shared_message_proto_init()
	file_controlplane_v1_workflow_contract_proto_msgTypes[2].OneofWrappers = []any{}
	file_controlplane_v1_workflow_contract_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_controlplane_v1_workflow_contract_proto_rawDesc), len(file_controlplane_v1_workflow_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_controlplane_v1_workflow_contract_proto_goTypes,
		DependencyIndexes: file_controlplane_v1_workflow_contract_proto_depIdxs,
		MessageInfos:      file_controlplane_v1_workflow_contract_proto_msgTypes,
	}.Build()
	File_controlplane_v1_workflow_contract_proto = out.File
	file_controlplane_v1_workflow_contract_proto_goTypes = nil
	file_controlplane_v1_workflow_contract_proto_depIdxs = nil
}
