FROM golang:1.24.6@sha256:2c89c41fb9efc3807029b59af69645867cfe978d2b877d475be0d72f6c6ce6f6 AS builder

FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY ./control-plane /
# Add plugins here
# NOTE: they are built by go-releaser in the builds section
# Make sure to update it acordingly if you add more plugins
COPY ./chainloop-plugin-discord-webhook /plugins/
COPY ./chainloop-plugin-dependency-track /plugins/
COPY ./chainloop-plugin-smtp /plugins/
# tmp is required for the plugins to run
COPY --from=builder /tmp /tmp

USER 1001

ENTRYPOINT [ "/control-plane", "--conf", "/data/conf"]
