FROM golang:1.26.5@sha256:079e59808d2d252516e27e3f3a9c003740dee7f75e55aa71528766d52bcfc16a AS builder

FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY ./control-plane /
# Add plugins here
# NOTE: they are built by go-releaser in the builds section
# Make sure to update it acordingly if you add more plugins
COPY ./chainloop-plugin-discord-webhook /plugins/
COPY ./chainloop-plugin-dependency-track /plugins/
COPY ./chainloop-plugin-smtp /plugins/
# tmp is required for the plugins to run
COPY --from=builder /tmp /tmp

USER 1001

ENTRYPOINT [ "/control-plane", "--conf", "/data/conf"]
