FROM golang:1.23@sha256:927112936d6b496ed95f55f362cc09da6e3e624ef868814c56d55bd7323e0959 AS builder

FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

COPY ./control-plane /
# Add plugins here
# NOTE: they are built by go-releaser in the builds section
# Make sure to update it acordingly if you add more plugins
COPY ./chainloop-plugin-discord-webhook /plugins/
COPY ./chainloop-plugin-dependency-track /plugins/
COPY ./chainloop-plugin-smtp /plugins/
# tmp is required for the plugins to run
COPY --from=builder /tmp /tmp

USER 1001

ENTRYPOINT [ "/control-plane", "--conf", "/data/conf"]
