run:
  skip-dirs:
    internal
  skip-files:
    dagger.gen.go

linters:
  enable:
    - dupl
    - gofmt
    - goimports
    - misspell
    - nakedret
    - revive
    - gosec
    - asciicheck
    - whitespace
    - errorlint
    - forbidigo
    - gocritic
    - importas
    - prealloc
    - stylecheck
    - unconvert
    - dogsled
    - goconst
    - exportloopref
    - gocyclo
    - goprintffuncname