version: "2"
linters:
  enable:
    - asciicheck
    - dogsled
    - dupl
    - errorlint
    - forbidigo
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - importas
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - whitespace
  exclusions:
    paths-except:
      - internal
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
