apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chainloop.controlplane.fullname" . }}
  labels:
    {{- include "chainloop.controlplane.labels" . | nindent 4 }}
type: Opaque
{{- $hmacpass := include "common.secrets.passwords.manage" (dict "secret" (include "chainloop.controlplane.fullname" .) "key" "generated_jws_hmac_secret" "providedValues" (list "controlplane.auth.passphrase") "context" $) }}
data:
  # We store it also as a different key so it can be reused during upgrades by the common.secrets.passwords.manage helper
  generated_jws_hmac_secret: {{ $hmacpass }}
stringData:
  {{- if and .Values.sentry .Values.sentry.enabled }}
    {{- fail "configuring sentry at the top level is no longer supported. Add the configuration to the controlplane section in the values.yaml file" }}
  {{- end -}}
  {{- if and .Values.controlplane.sentry .Values.controlplane.sentry.enabled }}
  config.observability.yaml: |
    {{- include "chainloop.sentry" .Values.controlplane.sentry | nindent 4 }}
  {{- end }}
  config.secret.yaml: |
    data:
      database:
        driver: pgx
        source: {{include "controlplane.database.connection_string" . }}

    credentials_service: {{- include "chainloop.credentials_service_settings" . | indent 6 }}

    auth:
      oidc:
        {{- with .Values.controlplane.auth }}
        redirect_url_scheme: {{ .redirectURLScheme }}
        domain: "{{ required "oidc URL endpoint required" .oidc.url }}"
        client_id: "{{ required "oidc clientID required" .oidc.clientID }}"
        client_secret: "{{ required "oidc clientSecret required" .oidc.clientSecret }}"
        {{- end }}

      # HMAC key used to sign the JWTs generated by the controlplane
      # The helper returns the base64 quoted value of the secret
      # We need to remove the quotes and then decoding it so it's compatible with the stringData stanza
      generated_jws_hmac_secret: {{ $hmacpass | replace "\"" "" | b64dec | quote }}

      # Private key used to sign the JWTs meant to be consumed by the CAS
      cas_robot_account_private_key_path: "/secrets/cas.private.key"
