apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chainloop.controlplane.fullname" . }}
  labels:
    {{- include "chainloop.controlplane.labels" . | nindent 4 }}
data:
  {{- if .Values.controlplane.allowList }}
  allow_list.yaml: |
    auth:
      allow_list:
        {{- range .Values.controlplane.allowList }}
        - {{ . | quote }}
        {{- end }}
  {{- end }}
  config.yaml: |
    server:
      http:
        addr: 0.0.0.0:8000
        timeout: 1s
        external_url: {{ include "chainloop.controlplane.external_url" . }}
      http_metrics:
        addr: 0.0.0.0:5000
      grpc:
        addr: 0.0.0.0:9000
        timeout: 10s
    cas_server:
      grpc:
        addr: {{ printf "%s-api:%.0f" (include "chainloop.cas.fullname" .) .Values.cas.serviceAPI.port }}
      insecure: true