{{- /*
Copyright Chainloop, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and .Values.controlplane.keylessSigning.enabled (eq "ejbcaCA" .Values.controlplane.keylessSigning.backend) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chainloop.controlplane.fullname" . }}-keyless-ejbca-ca
  labels:
    {{- include "chainloop.controlplane.labels" . | nindent 4 }}
type: Opaque
data:
  ejbca_ca.cert: {{ .Values.controlplane.keylessSigning.ejbcaCA.cert | b64enc | quote }}
  ejbca_ca.key: {{ .Values.controlplane.keylessSigning.ejbcaCA.key | b64enc | quote }}
{{- end }}