{{- if .Values.controlplane.ingressHTTP.enabled -}}
{{- $fullName := include "chainloop.controlplane.fullname" . -}}
{{- $svcPort := .Values.controlplane.service.port -}}
apiVersion: {{ include "common.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "chainloop.controlplane.labels" . | nindent 4 }}
  {{- with .Values.controlplane.ingressHTTP.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.controlplane.ingressHTTP.className (eq "true" (include "common.ingress.supportsIngressClassname" .)) }}
  ingressClassName: {{ .Values.controlplane.ingressHTTP.className | quote }}
  {{- end }}
  {{- if .Values.controlplane.ingressHTTP.tls }}
  tls:
    {{- range .Values.controlplane.ingressHTTP.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.controlplane.ingressHTTP.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" $fullName "servicePort" $svcPort "context" $)  | nindent 14 }}
          {{- end }}
    {{- end }}
{{- end }}
