apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chainloop.controlplane.fullname" . }}-jwt-cas
  labels:
    {{- include "chainloop.controlplane.labels" . | nindent 4 }}
type: Opaque
data:
  cas.private.key: {{ include "chainloop.casjwt.private_key" . | b64enc | quote  }}
