apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chainloop.controlplane.fullname" . }}-migrate
  labels:
    {{- include "chainloop.controlplane.migration.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "chainloop.controlplane.migration.labels" . | nindent 8 }}
    spec:
      {{- with .Values.controlplane.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: OnFailure
      securityContext:
        {{- toYaml .Values.controlplane.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          image: "{{ .Values.controlplane.migration.image.repository }}:{{ .Values.controlplane.migration.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.controlplane.image.pullPolicy }}
          args:
            - migrate
            - apply
            - --url
            - "{{include "controlplane.database.atlas_connection_string" . }}"
            - --dir
            - file:///migrations