{{- /*
Copyright Chainloop, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}


{{- if .Values.controlplane.keylessSigning.enabled }}
{{- range $index, $backend := .Values.controlplane.keylessSigning.backends }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chainloop.controlplane.fullname" $ }}-keyless-{{$backend.type | lower}}-{{$index}}
  labels:
    {{- include "chainloop.controlplane.labels" $ | nindent 4 }}
type: Opaque
data:
{{- if eq "fileCA" $backend.type }}
  file_ca.cert: {{ $backend.fileCA.cert | b64enc | quote }}
  file_ca.key: {{ $backend.fileCA.key | b64enc | quote }}
{{- else if eq "ejbcaCA" $backend.type }}
  ejbca_client.cert: {{ $backend.ejbcaCA.clientCert | b64enc | quote }}
  ejbca_client.key: {{ $backend.ejbcaCA.clientKey | b64enc | quote }}
  ejbca_ca.cert: {{ $backend.ejbcaCA.caCert | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
