apiVersion: v1
kind: Service
metadata:
  name: {{ include "chainloop.controlplane.fullname" . }}
  labels: {{- include "chainloop.controlplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controlplane.service.type }}
  ports:
    - port: {{ .Values.controlplane.service.port }}
      targetPort: {{ .Values.controlplane.service.targetPort }}
      protocol: TCP
      name: http
      nodePort: {{ include "chainloop.node_port" .Values.controlplane.service }}
  selector: {{- include "chainloop.controlplane.selectorLabels" . | nindent 4 }}
