{{- /*
Copyright Chainloop, Inc. All Rights Reserved.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "chainloop.controlplane.fullname" . }}-api
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: controlplane
  {{- if or .Values.controlplane.serviceAPI.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.controlplane.serviceAPI.annotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controlplane.serviceAPI.type }}
  {{- if and .Values.controlplane.serviceAPI.clusterIP (eq .Values.controlplane.serviceAPI.type "ClusterIP") }}
  clusterIP: {{ .Values.controlplane.serviceAPI.clusterIP }}
  {{- end }}
  {{- if .Values.controlplane.serviceAPI.sessionAffinity }}
  sessionAffinity: {{ .Values.controlplane.serviceAPI.sessionAffinity }}
  {{- end }}
  {{- if .Values.controlplane.serviceAPI.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.controlplane.serviceAPI.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.controlplane.serviceAPI.type "LoadBalancer") (eq .Values.controlplane.serviceAPI.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.controlplane.serviceAPI.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.controlplane.serviceAPI.type "LoadBalancer") (not (empty .Values.controlplane.serviceAPI.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.controlplane.serviceAPI.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.controlplane.serviceAPI.type "LoadBalancer") (not (empty .Values.controlplane.serviceAPI.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.controlplane.serviceAPI.loadBalancerIP }}
  {{- end }}
  ports:
    - name: grpc
      port: {{ .Values.controlplane.serviceAPI.ports.http }}
      {{- if not (eq .Values.controlplane.serviceAPI.ports.http .Values.controlplane.containerPorts.grpc) }}
      targetPort: {{ .Values.controlplane.containerPorts.grpc }}
      {{- end }}
      protocol: TCP
      {{- if and (or (eq .Values.controlplane.serviceAPI.type "NodePort") (eq .Values.controlplane.serviceAPI.type "LoadBalancer")) (not (empty .Values.controlplane.serviceAPI.nodePorts.http)) }}
      nodePort: {{ .Values.controlplane.serviceAPI.nodePorts.http }}
      {{- else if eq .Values.controlplane.serviceAPI.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.controlplane.serviceAPI.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.controlplane.serviceAPI.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  {{- $podLabels := include "common.tplvalues.merge" (dict "values" (list .Values.controlplane.podLabels .Values.commonLabels) "context" .) | fromYaml }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: controlplane
