apiVersion: workflowcontract.chainloop.dev/v1
kind: Policy
metadata:
  name: made-with-syft
spec:
  type: SBOM_SPDX_JSON
  embedded: |
    package main

    import future.keywords.in

    # Verifies that the SPDX was created with Syft
    
    deny[msg] {
      not made_with_syft

      msg := "Not made with syft"
    }

    made_with_syft {
      some creator in input.creationInfo.creators
      contains(creator, "syft")
    }
