name: Documentation Build and Test
on:
  pull_request:
    paths: ['docs/**']
  push:
    branches: ['main']
    paths: ['docs/**']
jobs:
  docs_build_and_test:
    name: Documentation Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: |
            docs
          sparse-checkout-cone-mode: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: yarn install & build
        run: yarn install && yarn build

