name: Test PR issue

on:
  push:
    branches:
      - fix-pr

jobs:
  release:
    name: Test PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Bump Chart Version
        run: .github/workflows/utils/bump-chart-version.sh deployment/chainloop v222.2.2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Bump Chart Version ${{ github.ref_name }}
          signoff: true
          base: main
          title: Bump Helm Chart Version => ${{ github.ref_name }}
          body: |
            A new Chainloop release is available! Bumping Helm Chart reference to ${{ github.ref_name }}
          labels: |
            automated
            helm